"""Differential tests against CPython's `json` module.

Generated by `scripts/gen_compat_cases.py`, which runs every case
through CPython and records what it produced. Do not edit by hand;
add cases to the generator and re-run it.
"""

from std.testing import TestSuite, assert_equal, assert_raises

from json import dumps, loads


def _check(
    text: StringSlice,
    default: StringSlice,
    compact: StringSlice,
    indented: StringSlice,
    sorted_keys: StringSlice,
    unescaped: StringSlice,
) raises:
    """Checks one decodable document against CPython's output.

    Args:
        text: The document to decode.
        default: What `json.dumps` produced with default options.
        compact: What it produced with `separators=(',', ':')`.
        indented: What it produced with `indent=2`.
        sorted_keys: What it produced with `sort_keys=True`.
        unescaped: What it produced with `ensure_ascii=False`.

    Raises:
        If any of the five renderings differs.
    """
    var doc = loads(text)
    assert_equal(dumps(doc), default, String(text))
    assert_equal(dumps(doc, separators=(",", ":")), compact, String(text))
    assert_equal(dumps(doc, indent=2), indented, String(text))
    assert_equal(dumps(doc, sort_keys=True), sorted_keys, String(text))
    assert_equal(dumps(doc, ensure_ascii=False), unescaped, String(text))


def test_matches_cpython_000() raises:
    _check(
        "null",
        "null",
        "null",
        "null",
        "null",
        "null",
    )
    _check(
        "true",
        "true",
        "true",
        "true",
        "true",
        "true",
    )
    _check(
        "false",
        "false",
        "false",
        "false",
        "false",
        "false",
    )
    _check(
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
    )
    _check(
        "-0",
        "0",
        "0",
        "0",
        "0",
        "0",
    )
    _check(
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
    )
    _check(
        "-1",
        "-1",
        "-1",
        "-1",
        "-1",
        "-1",
    )
    _check(
        "42",
        "42",
        "42",
        "42",
        "42",
        "42",
    )
    _check(
        "-42",
        "-42",
        "-42",
        "-42",
        "-42",
        "-42",
    )
    _check(
        "9223372036854775807",
        "9223372036854775807",
        "9223372036854775807",
        "9223372036854775807",
        "9223372036854775807",
        "9223372036854775807",
    )
    _check(
        "-9223372036854775808",
        "-9223372036854775808",
        "-9223372036854775808",
        "-9223372036854775808",
        "-9223372036854775808",
        "-9223372036854775808",
    )
    _check(
        "0.0",
        "0.0",
        "0.0",
        "0.0",
        "0.0",
        "0.0",
    )


def test_matches_cpython_001() raises:
    _check(
        "-0.0",
        "-0.0",
        "-0.0",
        "-0.0",
        "-0.0",
        "-0.0",
    )
    _check(
        "1.0",
        "1.0",
        "1.0",
        "1.0",
        "1.0",
        "1.0",
    )
    _check(
        "-1.5",
        "-1.5",
        "-1.5",
        "-1.5",
        "-1.5",
        "-1.5",
    )
    _check(
        "0.1",
        "0.1",
        "0.1",
        "0.1",
        "0.1",
        "0.1",
    )
    _check(
        "1e3",
        "1000.0",
        "1000.0",
        "1000.0",
        "1000.0",
        "1000.0",
    )
    _check(
        "1E3",
        "1000.0",
        "1000.0",
        "1000.0",
        "1000.0",
        "1000.0",
    )
    _check(
        "1e+3",
        "1000.0",
        "1000.0",
        "1000.0",
        "1000.0",
        "1000.0",
    )
    _check(
        "1e-3",
        "0.001",
        "0.001",
        "0.001",
        "0.001",
        "0.001",
    )
    _check(
        "1.5e10",
        "15000000000.0",
        "15000000000.0",
        "15000000000.0",
        "15000000000.0",
        "15000000000.0",
    )
    _check(
        "-2.25e-8",
        "-2.25e-08",
        "-2.25e-08",
        "-2.25e-08",
        "-2.25e-08",
        "-2.25e-08",
    )
    _check(
        "3.141592653589793",
        "3.141592653589793",
        "3.141592653589793",
        "3.141592653589793",
        "3.141592653589793",
        "3.141592653589793",
    )
    _check(
        "1.7976931348623157e308",
        "1.7976931348623157e+308",
        "1.7976931348623157e+308",
        "1.7976931348623157e+308",
        "1.7976931348623157e+308",
        "1.7976931348623157e+308",
    )


def test_matches_cpython_002() raises:
    _check(
        "2.2250738585072014e-308",
        "2.2250738585072014e-308",
        "2.2250738585072014e-308",
        "2.2250738585072014e-308",
        "2.2250738585072014e-308",
        "2.2250738585072014e-308",
    )
    _check(
        "5e-324",
        "5e-324",
        "5e-324",
        "5e-324",
        "5e-324",
        "5e-324",
    )
    _check(
        "1e400",
        "Infinity",
        "Infinity",
        "Infinity",
        "Infinity",
        "Infinity",
    )
    _check(
        "-1e400",
        "-Infinity",
        "-Infinity",
        "-Infinity",
        "-Infinity",
        "-Infinity",
    )
    _check(
        "0.30000000000000004",
        "0.30000000000000004",
        "0.30000000000000004",
        "0.30000000000000004",
        "0.30000000000000004",
        "0.30000000000000004",
    )
    _check(
        "123456789.123456789",
        "123456789.12345679",
        "123456789.12345679",
        "123456789.12345679",
        "123456789.12345679",
        "123456789.12345679",
    )
    _check(
        "1000000000000000000000.0",
        "1e+21",
        "1e+21",
        "1e+21",
        "1e+21",
        "1e+21",
    )
    _check(
        "NaN",
        "NaN",
        "NaN",
        "NaN",
        "NaN",
        "NaN",
    )
    _check(
        "Infinity",
        "Infinity",
        "Infinity",
        "Infinity",
        "Infinity",
        "Infinity",
    )
    _check(
        "-Infinity",
        "-Infinity",
        "-Infinity",
        "-Infinity",
        "-Infinity",
        "-Infinity",
    )
    _check(
        "\"\"",
        "\"\"",
        "\"\"",
        "\"\"",
        "\"\"",
        "\"\"",
    )
    _check(
        "\"a\"",
        "\"a\"",
        "\"a\"",
        "\"a\"",
        "\"a\"",
        "\"a\"",
    )


def test_matches_cpython_003() raises:
    _check(
        "\"hello world\"",
        "\"hello world\"",
        "\"hello world\"",
        "\"hello world\"",
        "\"hello world\"",
        "\"hello world\"",
    )
    _check(
        "\"tab\\there\"",
        "\"tab\\there\"",
        "\"tab\\there\"",
        "\"tab\\there\"",
        "\"tab\\there\"",
        "\"tab\\there\"",
    )
    _check(
        "\"nl\\nhere\"",
        "\"nl\\nhere\"",
        "\"nl\\nhere\"",
        "\"nl\\nhere\"",
        "\"nl\\nhere\"",
        "\"nl\\nhere\"",
    )
    _check(
        "\"quote\\\"inside\"",
        "\"quote\\\"inside\"",
        "\"quote\\\"inside\"",
        "\"quote\\\"inside\"",
        "\"quote\\\"inside\"",
        "\"quote\\\"inside\"",
    )
    _check(
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
    )
    _check(
        "\"solidus\\/here\"",
        "\"solidus/here\"",
        "\"solidus/here\"",
        "\"solidus/here\"",
        "\"solidus/here\"",
        "\"solidus/here\"",
    )
    _check(
        "\"\\b\\f\\n\\r\\t\"",
        "\"\\b\\f\\n\\r\\t\"",
        "\"\\b\\f\\n\\r\\t\"",
        "\"\\b\\f\\n\\r\\t\"",
        "\"\\b\\f\\n\\r\\t\"",
        "\"\\b\\f\\n\\r\\t\"",
    )
    _check(
        "\"\\u0000\"",
        "\"\\u0000\"",
        "\"\\u0000\"",
        "\"\\u0000\"",
        "\"\\u0000\"",
        "\"\\u0000\"",
    )
    _check(
        "\"\\u001f\"",
        "\"\\u001f\"",
        "\"\\u001f\"",
        "\"\\u001f\"",
        "\"\\u001f\"",
        "\"\\u001f\"",
    )
    _check(
        "\"\\u0020\"",
        "\" \"",
        "\" \"",
        "\" \"",
        "\" \"",
        "\" \"",
    )
    _check(
        "\"\\u007f\"",
        "\"\\u007f\"",
        "\"\\u007f\"",
        "\"\\u007f\"",
        "\"\\u007f\"",
        "\"\x7f\"",
    )
    _check(
        "\"\\u00e9\"",
        "\"\\u00e9\"",
        "\"\\u00e9\"",
        "\"\\u00e9\"",
        "\"\\u00e9\"",
        "\"é\"",
    )


def test_matches_cpython_004() raises:
    _check(
        "\"\\u65e5\\u672c\\u8a9e\"",
        "\"\\u65e5\\u672c\\u8a9e\"",
        "\"\\u65e5\\u672c\\u8a9e\"",
        "\"\\u65e5\\u672c\\u8a9e\"",
        "\"\\u65e5\\u672c\\u8a9e\"",
        "\"日本語\"",
    )
    _check(
        "\"\\ud83d\\ude00\"",
        "\"\\ud83d\\ude00\"",
        "\"\\ud83d\\ude00\"",
        "\"\\ud83d\\ude00\"",
        "\"\\ud83d\\ude00\"",
        "\"😀\"",
    )
    _check(
        "\"\\uffff\"",
        "\"\\uffff\"",
        "\"\\uffff\"",
        "\"\\uffff\"",
        "\"\\uffff\"",
        "\"￿\"",
    )
    _check(
        "\"mixed \\u00e9 text \\ud83d\\ude00 end\"",
        "\"mixed \\u00e9 text \\ud83d\\ude00 end\"",
        "\"mixed \\u00e9 text \\ud83d\\ude00 end\"",
        "\"mixed \\u00e9 text \\ud83d\\ude00 end\"",
        "\"mixed \\u00e9 text \\ud83d\\ude00 end\"",
        "\"mixed é text 😀 end\"",
    )
    _check(
        "\"日本語\"",
        "\"\\u65e5\\u672c\\u8a9e\"",
        "\"\\u65e5\\u672c\\u8a9e\"",
        "\"\\u65e5\\u672c\\u8a9e\"",
        "\"\\u65e5\\u672c\\u8a9e\"",
        "\"日本語\"",
    )
    _check(
        "\"emoji 😀 here\"",
        "\"emoji \\ud83d\\ude00 here\"",
        "\"emoji \\ud83d\\ude00 here\"",
        "\"emoji \\ud83d\\ude00 here\"",
        "\"emoji \\ud83d\\ude00 here\"",
        "\"emoji 😀 here\"",
    )
    _check(
        "\"\\u0041\\u0042\"",
        "\"AB\"",
        "\"AB\"",
        "\"AB\"",
        "\"AB\"",
        "\"AB\"",
    )
    _check(
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
    )
    _check(
        "{}",
        "{}",
        "{}",
        "{}",
        "{}",
        "{}",
    )
    _check(
        "[1]",
        "[1]",
        "[1]",
        "[\n  1\n]",
        "[1]",
        "[1]",
    )
    _check(
        "[1,2,3]",
        "[1, 2, 3]",
        "[1,2,3]",
        "[\n  1,\n  2,\n  3\n]",
        "[1, 2, 3]",
        "[1, 2, 3]",
    )
    _check(
        "[\"a\",\"b\"]",
        "[\"a\", \"b\"]",
        "[\"a\",\"b\"]",
        "[\n  \"a\",\n  \"b\"\n]",
        "[\"a\", \"b\"]",
        "[\"a\", \"b\"]",
    )


def test_matches_cpython_005() raises:
    _check(
        "[[]]",
        "[[]]",
        "[[]]",
        "[\n  []\n]",
        "[[]]",
        "[[]]",
    )
    _check(
        "[[[[[]]]]]",
        "[[[[[]]]]]",
        "[[[[[]]]]]",
        "[\n  [\n    [\n      [\n        []\n      ]\n    ]\n  ]\n]",
        "[[[[[]]]]]",
        "[[[[[]]]]]",
    )
    _check(
        "[null,true,false,1,1.5,\"s\",[],{}]",
        "[null, true, false, 1, 1.5, \"s\", [], {}]",
        "[null,true,false,1,1.5,\"s\",[],{}]",
        "[\n  null,\n  true,\n  false,\n  1,\n  1.5,\n  \"s\",\n  [],\n  {}\n]",
        "[null, true, false, 1, 1.5, \"s\", [], {}]",
        "[null, true, false, 1, 1.5, \"s\", [], {}]",
    )
    _check(
        "{\"a\":1}",
        "{\"a\": 1}",
        "{\"a\":1}",
        "{\n  \"a\": 1\n}",
        "{\"a\": 1}",
        "{\"a\": 1}",
    )
    _check(
        "{\"a\":1,\"b\":2}",
        "{\"a\": 1, \"b\": 2}",
        "{\"a\":1,\"b\":2}",
        "{\n  \"a\": 1,\n  \"b\": 2\n}",
        "{\"a\": 1, \"b\": 2}",
        "{\"a\": 1, \"b\": 2}",
    )
    _check(
        "{\"\":1}",
        "{\"\": 1}",
        "{\"\":1}",
        "{\n  \"\": 1\n}",
        "{\"\": 1}",
        "{\"\": 1}",
    )
    _check(
        "{\"a\":{\"b\":{\"c\":1}}}",
        "{\"a\": {\"b\": {\"c\": 1}}}",
        "{\"a\":{\"b\":{\"c\":1}}}",
        "{\n  \"a\": {\n    \"b\": {\n      \"c\": 1\n    }\n  }\n}",
        "{\"a\": {\"b\": {\"c\": 1}}}",
        "{\"a\": {\"b\": {\"c\": 1}}}",
    )
    _check(
        "{\"a\":[1,2],\"b\":{\"c\":[3,{\"d\":null}]}}",
        "{\"a\": [1, 2], \"b\": {\"c\": [3, {\"d\": null}]}}",
        "{\"a\":[1,2],\"b\":{\"c\":[3,{\"d\":null}]}}",
        "{\n  \"a\": [\n    1,\n    2\n  ],\n  \"b\": {\n    \"c\": [\n      3,\n      {\n        \"d\": null\n      }\n    ]\n  }\n}",
        "{\"a\": [1, 2], \"b\": {\"c\": [3, {\"d\": null}]}}",
        "{\"a\": [1, 2], \"b\": {\"c\": [3, {\"d\": null}]}}",
    )
    _check(
        "{\"a\":1,\"a\":2}",
        "{\"a\": 2}",
        "{\"a\":2}",
        "{\n  \"a\": 2\n}",
        "{\"a\": 2}",
        "{\"a\": 2}",
    )
    _check(
        "{\"a\":1,\"b\":2,\"a\":3}",
        "{\"a\": 3, \"b\": 2}",
        "{\"a\":3,\"b\":2}",
        "{\n  \"a\": 3,\n  \"b\": 2\n}",
        "{\"a\": 3, \"b\": 2}",
        "{\"a\": 3, \"b\": 2}",
    )
    _check(
        "{\"dup\":1,\"x\":0,\"dup\":2,\"y\":0,\"dup\":3}",
        "{\"dup\": 3, \"x\": 0, \"y\": 0}",
        "{\"dup\":3,\"x\":0,\"y\":0}",
        "{\n  \"dup\": 3,\n  \"x\": 0,\n  \"y\": 0\n}",
        "{\"dup\": 3, \"x\": 0, \"y\": 0}",
        "{\"dup\": 3, \"x\": 0, \"y\": 0}",
    )
    _check(
        "  [ 1 , 2 ]  ",
        "[1, 2]",
        "[1,2]",
        "[\n  1,\n  2\n]",
        "[1, 2]",
        "[1, 2]",
    )


def test_matches_cpython_006() raises:
    _check(
        "\n{\n\"a\"\t:\r1\n}\n",
        "{\"a\": 1}",
        "{\"a\":1}",
        "{\n  \"a\": 1\n}",
        "{\"a\": 1}",
        "{\"a\": 1}",
    )
    _check(
        "{\"unicode key 日本語\": \"value\"}",
        "{\"unicode key \\u65e5\\u672c\\u8a9e\": \"value\"}",
        "{\"unicode key \\u65e5\\u672c\\u8a9e\":\"value\"}",
        "{\n  \"unicode key \\u65e5\\u672c\\u8a9e\": \"value\"\n}",
        "{\"unicode key \\u65e5\\u672c\\u8a9e\": \"value\"}",
        "{\"unicode key 日本語\": \"value\"}",
    )
    _check(
        "[[{\"emoji \\ud83d\\ude0016\": {\"tab\\there17\": -171405.24022307107, \"emoji \\ud83d\\ude0026\": 3289023371262690137, \"quote\\\"9\": null, \"a27\": \"quote\\\"\"}, \"back\\\\slash15\": -7}, {}, -628704.5596490288]]",
        "[[{\"emoji \\ud83d\\ude0016\": {\"tab\\there17\": -171405.24022307107, \"emoji \\ud83d\\ude0026\": 3289023371262690137, \"quote\\\"9\": null, \"a27\": \"quote\\\"\"}, \"back\\\\slash15\": -7}, {}, -628704.5596490288]]",
        "[[{\"emoji \\ud83d\\ude0016\":{\"tab\\there17\":-171405.24022307107,\"emoji \\ud83d\\ude0026\":3289023371262690137,\"quote\\\"9\":null,\"a27\":\"quote\\\"\"},\"back\\\\slash15\":-7},{},-628704.5596490288]]",
        "[\n  [\n    {\n      \"emoji \\ud83d\\ude0016\": {\n        \"tab\\there17\": -171405.24022307107,\n        \"emoji \\ud83d\\ude0026\": 3289023371262690137,\n        \"quote\\\"9\": null,\n        \"a27\": \"quote\\\"\"\n      },\n      \"back\\\\slash15\": -7\n    },\n    {},\n    -628704.5596490288\n  ]\n]",
        "[[{\"back\\\\slash15\": -7, \"emoji \\ud83d\\ude0016\": {\"a27\": \"quote\\\"\", \"emoji \\ud83d\\ude0026\": 3289023371262690137, \"quote\\\"9\": null, \"tab\\there17\": -171405.24022307107}}, {}, -628704.5596490288]]",
        "[[{\"emoji 😀16\": {\"tab\\there17\": -171405.24022307107, \"emoji 😀26\": 3289023371262690137, \"quote\\\"9\": null, \"a27\": \"quote\\\"\"}, \"back\\\\slash15\": -7}, {}, -628704.5596490288]]",
    )
    _check(
        "null",
        "null",
        "null",
        "null",
        "null",
        "null",
    )
    _check(
        "false",
        "false",
        "false",
        "false",
        "false",
        "false",
    )
    _check(
        "null",
        "null",
        "null",
        "null",
        "null",
        "null",
    )
    _check(
        "{}",
        "{}",
        "{}",
        "{}",
        "{}",
        "{}",
    )
    _check(
        "0.1",
        "0.1",
        "0.1",
        "0.1",
        "0.1",
        "0.1",
    )
    _check(
        "{\"quote\\\"27\": 0.1, \"a16\": [{\"quote\\\"27\": {\"long long long long long long long long 22\": -915098.0114332838, \"\\u0000\\u0001\\u001f24\": -1, \"long long long long long long long long 27\": -4079658451637310350, \"long long long long long long long long 25\": 470734.64825133234}, \"quote\\\"5\": {\"tab\\there5\": null}, \"long long long long long long long long 29\": {\"long long long long long long long long 1\": true, \"a25\": -3444619140665168853, \"long long long long long long long long 21\": -900141.7847488717}}], \"nl\\nhere29\": true, \"tab\\there6\": 213337.79262615275}",
        "{\"quote\\\"27\": 0.1, \"a16\": [{\"quote\\\"27\": {\"long long long long long long long long 22\": -915098.0114332838, \"\\u0000\\u0001\\u001f24\": -1, \"long long long long long long long long 27\": -4079658451637310350, \"long long long long long long long long 25\": 470734.64825133234}, \"quote\\\"5\": {\"tab\\there5\": null}, \"long long long long long long long long 29\": {\"long long long long long long long long 1\": true, \"a25\": -3444619140665168853, \"long long long long long long long long 21\": -900141.7847488717}}], \"nl\\nhere29\": true, \"tab\\there6\": 213337.79262615275}",
        "{\"quote\\\"27\":0.1,\"a16\":[{\"quote\\\"27\":{\"long long long long long long long long 22\":-915098.0114332838,\"\\u0000\\u0001\\u001f24\":-1,\"long long long long long long long long 27\":-4079658451637310350,\"long long long long long long long long 25\":470734.64825133234},\"quote\\\"5\":{\"tab\\there5\":null},\"long long long long long long long long 29\":{\"long long long long long long long long 1\":true,\"a25\":-3444619140665168853,\"long long long long long long long long 21\":-900141.7847488717}}],\"nl\\nhere29\":true,\"tab\\there6\":213337.79262615275}",
        "{\n  \"quote\\\"27\": 0.1,\n  \"a16\": [\n    {\n      \"quote\\\"27\": {\n        \"long long long long long long long long 22\": -915098.0114332838,\n        \"\\u0000\\u0001\\u001f24\": -1,\n        \"long long long long long long long long 27\": -4079658451637310350,\n        \"long long long long long long long long 25\": 470734.64825133234\n      },\n      \"quote\\\"5\": {\n        \"tab\\there5\": null\n      },\n      \"long long long long long long long long 29\": {\n        \"long long long long long long long long 1\": true,\n        \"a25\": -3444619140665168853,\n        \"long long long long long long long long 21\": -900141.7847488717\n      }\n    }\n  ],\n  \"nl\\nhere29\": true,\n  \"tab\\there6\": 213337.79262615275\n}",
        "{\"a16\": [{\"long long long long long long long long 29\": {\"a25\": -3444619140665168853, \"long long long long long long long long 1\": true, \"long long long long long long long long 21\": -900141.7847488717}, \"quote\\\"27\": {\"\\u0000\\u0001\\u001f24\": -1, \"long long long long long long long long 22\": -915098.0114332838, \"long long long long long long long long 25\": 470734.64825133234, \"long long long long long long long long 27\": -4079658451637310350}, \"quote\\\"5\": {\"tab\\there5\": null}}], \"nl\\nhere29\": true, \"quote\\\"27\": 0.1, \"tab\\there6\": 213337.79262615275}",
        "{\"quote\\\"27\": 0.1, \"a16\": [{\"quote\\\"27\": {\"long long long long long long long long 22\": -915098.0114332838, \"\\u0000\\u0001\\u001f24\": -1, \"long long long long long long long long 27\": -4079658451637310350, \"long long long long long long long long 25\": 470734.64825133234}, \"quote\\\"5\": {\"tab\\there5\": null}, \"long long long long long long long long 29\": {\"long long long long long long long long 1\": true, \"a25\": -3444619140665168853, \"long long long long long long long long 21\": -900141.7847488717}}], \"nl\\nhere29\": true, \"tab\\there6\": 213337.79262615275}",
    )
    _check(
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
    )
    _check(
        "6",
        "6",
        "6",
        "6",
        "6",
        "6",
    )
    _check(
        "null",
        "null",
        "null",
        "null",
        "null",
        "null",
    )


def test_matches_cpython_007() raises:
    _check(
        "{\"6\": {\"a29\": 0, \"21\": {}}, \"日本語21\": null}",
        "{\"6\": {\"a29\": 0, \"21\": {}}, \"\\u65e5\\u672c\\u8a9e21\": null}",
        "{\"6\":{\"a29\":0,\"21\":{}},\"\\u65e5\\u672c\\u8a9e21\":null}",
        "{\n  \"6\": {\n    \"a29\": 0,\n    \"21\": {}\n  },\n  \"\\u65e5\\u672c\\u8a9e21\": null\n}",
        "{\"6\": {\"21\": {}, \"a29\": 0}, \"\\u65e5\\u672c\\u8a9e21\": null}",
        "{\"6\": {\"a29\": 0, \"21\": {}}, \"日本語21\": null}",
    )
    _check(
        "-720057.8474614798",
        "-720057.8474614798",
        "-720057.8474614798",
        "-720057.8474614798",
        "-720057.8474614798",
        "-720057.8474614798",
    )
    _check(
        "{\"quote\\\"27\": [true, {\"key0\": \"\\u65e5\\u672c\\u8a9e\", \"long long long long long long long long 5\": false}, null]}",
        "{\"quote\\\"27\": [true, {\"key0\": \"\\u65e5\\u672c\\u8a9e\", \"long long long long long long long long 5\": false}, null]}",
        "{\"quote\\\"27\":[true,{\"key0\":\"\\u65e5\\u672c\\u8a9e\",\"long long long long long long long long 5\":false},null]}",
        "{\n  \"quote\\\"27\": [\n    true,\n    {\n      \"key0\": \"\\u65e5\\u672c\\u8a9e\",\n      \"long long long long long long long long 5\": false\n    },\n    null\n  ]\n}",
        "{\"quote\\\"27\": [true, {\"key0\": \"\\u65e5\\u672c\\u8a9e\", \"long long long long long long long long 5\": false}, null]}",
        "{\"quote\\\"27\": [true, {\"key0\": \"日本語\", \"long long long long long long long long 5\": false}, null]}",
    )
    _check(
        "-2995680678158752102",
        "-2995680678158752102",
        "-2995680678158752102",
        "-2995680678158752102",
        "-2995680678158752102",
        "-2995680678158752102",
    )
    _check(
        "true",
        "true",
        "true",
        "true",
        "true",
        "true",
    )
    _check(
        "1e+300",
        "1e+300",
        "1e+300",
        "1e+300",
        "1e+300",
        "1e+300",
    )
    _check(
        "\"nl\\nhere\"",
        "\"nl\\nhere\"",
        "\"nl\\nhere\"",
        "\"nl\\nhere\"",
        "\"nl\\nhere\"",
        "\"nl\\nhere\"",
    )
    _check(
        "-244187.42294072662",
        "-244187.42294072662",
        "-244187.42294072662",
        "-244187.42294072662",
        "-244187.42294072662",
        "-244187.42294072662",
    )
    _check(
        "3695524776491828279",
        "3695524776491828279",
        "3695524776491828279",
        "3695524776491828279",
        "3695524776491828279",
        "3695524776491828279",
    )
    _check(
        "{\"nl\\nhere22\": {\"key25\": {\"nl\\nhere22\": [\"nl\\nhere\"], \"long long long long long long long long 20\": 0.3333333333333333, \"\\u65e5\\u672c\\u8a9e9\": {\"11\": 0.1, \"\\u65e5\\u672c\\u8a9e18\": null, \"a3\": \"back\\\\slash\"}}, \"emoji \\ud83d\\ude0016\": {\"quote\\\"25\": [-4163952072109002540]}, \"back\\\\slash8\": {\"back\\\\slash4\": {\"emoji \\ud83d\\ude0026\": -868091121360956976, \"1\": 0.1, \"long long long long long long long long 1\": 9}, \"tab\\there6\": true, \"4\": 4, \"a1\": [2, \"\\u007f del\", null]}}, \"\\u0000\\u0001\\u001f20\": [\"nl\\nhere\", {\"long long long long long long long long 12\": false, \"a15\": [-2459635240082200191, null, 4354507528516781203]}], \"\\u007f del1\": [-305458.75450509414]}",
        "{\"nl\\nhere22\": {\"key25\": {\"nl\\nhere22\": [\"nl\\nhere\"], \"long long long long long long long long 20\": 0.3333333333333333, \"\\u65e5\\u672c\\u8a9e9\": {\"11\": 0.1, \"\\u65e5\\u672c\\u8a9e18\": null, \"a3\": \"back\\\\slash\"}}, \"emoji \\ud83d\\ude0016\": {\"quote\\\"25\": [-4163952072109002540]}, \"back\\\\slash8\": {\"back\\\\slash4\": {\"emoji \\ud83d\\ude0026\": -868091121360956976, \"1\": 0.1, \"long long long long long long long long 1\": 9}, \"tab\\there6\": true, \"4\": 4, \"a1\": [2, \"\\u007f del\", null]}}, \"\\u0000\\u0001\\u001f20\": [\"nl\\nhere\", {\"long long long long long long long long 12\": false, \"a15\": [-2459635240082200191, null, 4354507528516781203]}], \"\\u007f del1\": [-305458.75450509414]}",
        "{\"nl\\nhere22\":{\"key25\":{\"nl\\nhere22\":[\"nl\\nhere\"],\"long long long long long long long long 20\":0.3333333333333333,\"\\u65e5\\u672c\\u8a9e9\":{\"11\":0.1,\"\\u65e5\\u672c\\u8a9e18\":null,\"a3\":\"back\\\\slash\"}},\"emoji \\ud83d\\ude0016\":{\"quote\\\"25\":[-4163952072109002540]},\"back\\\\slash8\":{\"back\\\\slash4\":{\"emoji \\ud83d\\ude0026\":-868091121360956976,\"1\":0.1,\"long long long long long long long long 1\":9},\"tab\\there6\":true,\"4\":4,\"a1\":[2,\"\\u007f del\",null]}},\"\\u0000\\u0001\\u001f20\":[\"nl\\nhere\",{\"long long long long long long long long 12\":false,\"a15\":[-2459635240082200191,null,4354507528516781203]}],\"\\u007f del1\":[-305458.75450509414]}",
        "{\n  \"nl\\nhere22\": {\n    \"key25\": {\n      \"nl\\nhere22\": [\n        \"nl\\nhere\"\n      ],\n      \"long long long long long long long long 20\": 0.3333333333333333,\n      \"\\u65e5\\u672c\\u8a9e9\": {\n        \"11\": 0.1,\n        \"\\u65e5\\u672c\\u8a9e18\": null,\n        \"a3\": \"back\\\\slash\"\n      }\n    },\n    \"emoji \\ud83d\\ude0016\": {\n      \"quote\\\"25\": [\n        -4163952072109002540\n      ]\n    },\n    \"back\\\\slash8\": {\n      \"back\\\\slash4\": {\n        \"emoji \\ud83d\\ude0026\": -868091121360956976,\n        \"1\": 0.1,\n        \"long long long long long long long long 1\": 9\n      },\n      \"tab\\there6\": true,\n      \"4\": 4,\n      \"a1\": [\n        2,\n        \"\\u007f del\",\n        null\n      ]\n    }\n  },\n  \"\\u0000\\u0001\\u001f20\": [\n    \"nl\\nhere\",\n    {\n      \"long long long long long long long long 12\": false,\n      \"a15\": [\n        -2459635240082200191,\n        null,\n        4354507528516781203\n      ]\n    }\n  ],\n  \"\\u007f del1\": [\n    -305458.75450509414\n  ]\n}",
        "{\"\\u0000\\u0001\\u001f20\": [\"nl\\nhere\", {\"a15\": [-2459635240082200191, null, 4354507528516781203], \"long long long long long long long long 12\": false}], \"nl\\nhere22\": {\"back\\\\slash8\": {\"4\": 4, \"a1\": [2, \"\\u007f del\", null], \"back\\\\slash4\": {\"1\": 0.1, \"emoji \\ud83d\\ude0026\": -868091121360956976, \"long long long long long long long long 1\": 9}, \"tab\\there6\": true}, \"emoji \\ud83d\\ude0016\": {\"quote\\\"25\": [-4163952072109002540]}, \"key25\": {\"long long long long long long long long 20\": 0.3333333333333333, \"nl\\nhere22\": [\"nl\\nhere\"], \"\\u65e5\\u672c\\u8a9e9\": {\"11\": 0.1, \"a3\": \"back\\\\slash\", \"\\u65e5\\u672c\\u8a9e18\": null}}}, \"\\u007f del1\": [-305458.75450509414]}",
        "{\"nl\\nhere22\": {\"key25\": {\"nl\\nhere22\": [\"nl\\nhere\"], \"long long long long long long long long 20\": 0.3333333333333333, \"日本語9\": {\"11\": 0.1, \"日本語18\": null, \"a3\": \"back\\\\slash\"}}, \"emoji 😀16\": {\"quote\\\"25\": [-4163952072109002540]}, \"back\\\\slash8\": {\"back\\\\slash4\": {\"emoji 😀26\": -868091121360956976, \"1\": 0.1, \"long long long long long long long long 1\": 9}, \"tab\\there6\": true, \"4\": 4, \"a1\": [2, \"\x7f del\", null]}}, \"\\u0000\\u0001\\u001f20\": [\"nl\\nhere\", {\"long long long long long long long long 12\": false, \"a15\": [-2459635240082200191, null, 4354507528516781203]}], \"\x7f del1\": [-305458.75450509414]}",
    )
    _check(
        "{}",
        "{}",
        "{}",
        "{}",
        "{}",
        "{}",
    )
    _check(
        "-0.0",
        "-0.0",
        "-0.0",
        "-0.0",
        "-0.0",
        "-0.0",
    )


def test_matches_cpython_008() raises:
    _check(
        "{\"a23\": {\"\\u65e5\\u672c\\u8a9e20\": {}}, \"long long long long long long long long 8\": null}",
        "{\"a23\": {\"\\u65e5\\u672c\\u8a9e20\": {}}, \"long long long long long long long long 8\": null}",
        "{\"a23\":{\"\\u65e5\\u672c\\u8a9e20\":{}},\"long long long long long long long long 8\":null}",
        "{\n  \"a23\": {\n    \"\\u65e5\\u672c\\u8a9e20\": {}\n  },\n  \"long long long long long long long long 8\": null\n}",
        "{\"a23\": {\"\\u65e5\\u672c\\u8a9e20\": {}}, \"long long long long long long long long 8\": null}",
        "{\"a23\": {\"日本語20\": {}}, \"long long long long long long long long 8\": null}",
    )
    _check(
        "-261081.66596157686",
        "-261081.66596157686",
        "-261081.66596157686",
        "-261081.66596157686",
        "-261081.66596157686",
        "-261081.66596157686",
    )
    _check(
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
    )
    _check(
        "-155248.27937470807",
        "-155248.27937470807",
        "-155248.27937470807",
        "-155248.27937470807",
        "-155248.27937470807",
        "-155248.27937470807",
    )
    _check(
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
    )
    _check(
        "{\"tab\\there21\": {\"emoji 😀3\": {\"9\": [-0.0, null, \"emoji 😀\"]}, \"\x7f del23\": [0.0, {\"19\": \"emoji 😀\", \"long long long long long long long long 7\": null}, [\"\"]]}, \"quote\\\"8\": \"\", \"key16\": null, \"日本語21\": -4594868541721590454}",
        "{\"tab\\there21\": {\"emoji \\ud83d\\ude003\": {\"9\": [-0.0, null, \"emoji \\ud83d\\ude00\"]}, \"\\u007f del23\": [0.0, {\"19\": \"emoji \\ud83d\\ude00\", \"long long long long long long long long 7\": null}, [\"\"]]}, \"quote\\\"8\": \"\", \"key16\": null, \"\\u65e5\\u672c\\u8a9e21\": -4594868541721590454}",
        "{\"tab\\there21\":{\"emoji \\ud83d\\ude003\":{\"9\":[-0.0,null,\"emoji \\ud83d\\ude00\"]},\"\\u007f del23\":[0.0,{\"19\":\"emoji \\ud83d\\ude00\",\"long long long long long long long long 7\":null},[\"\"]]},\"quote\\\"8\":\"\",\"key16\":null,\"\\u65e5\\u672c\\u8a9e21\":-4594868541721590454}",
        "{\n  \"tab\\there21\": {\n    \"emoji \\ud83d\\ude003\": {\n      \"9\": [\n        -0.0,\n        null,\n        \"emoji \\ud83d\\ude00\"\n      ]\n    },\n    \"\\u007f del23\": [\n      0.0,\n      {\n        \"19\": \"emoji \\ud83d\\ude00\",\n        \"long long long long long long long long 7\": null\n      },\n      [\n        \"\"\n      ]\n    ]\n  },\n  \"quote\\\"8\": \"\",\n  \"key16\": null,\n  \"\\u65e5\\u672c\\u8a9e21\": -4594868541721590454\n}",
        "{\"key16\": null, \"quote\\\"8\": \"\", \"tab\\there21\": {\"emoji \\ud83d\\ude003\": {\"9\": [-0.0, null, \"emoji \\ud83d\\ude00\"]}, \"\\u007f del23\": [0.0, {\"19\": \"emoji \\ud83d\\ude00\", \"long long long long long long long long 7\": null}, [\"\"]]}, \"\\u65e5\\u672c\\u8a9e21\": -4594868541721590454}",
        "{\"tab\\there21\": {\"emoji 😀3\": {\"9\": [-0.0, null, \"emoji 😀\"]}, \"\x7f del23\": [0.0, {\"19\": \"emoji 😀\", \"long long long long long long long long 7\": null}, [\"\"]]}, \"quote\\\"8\": \"\", \"key16\": null, \"日本語21\": -4594868541721590454}",
    )
    _check(
        "[{}, {}, {\"long long long long long long long long 26\": [2], \"emoji 😀21\": [{\"nl\\nhere21\": -1, \"\\u0000\\u0001\\u001f11\": false}, {\"back\\\\slash23\": 1e+300}, []]}]",
        "[{}, {}, {\"long long long long long long long long 26\": [2], \"emoji \\ud83d\\ude0021\": [{\"nl\\nhere21\": -1, \"\\u0000\\u0001\\u001f11\": false}, {\"back\\\\slash23\": 1e+300}, []]}]",
        "[{},{},{\"long long long long long long long long 26\":[2],\"emoji \\ud83d\\ude0021\":[{\"nl\\nhere21\":-1,\"\\u0000\\u0001\\u001f11\":false},{\"back\\\\slash23\":1e+300},[]]}]",
        "[\n  {},\n  {},\n  {\n    \"long long long long long long long long 26\": [\n      2\n    ],\n    \"emoji \\ud83d\\ude0021\": [\n      {\n        \"nl\\nhere21\": -1,\n        \"\\u0000\\u0001\\u001f11\": false\n      },\n      {\n        \"back\\\\slash23\": 1e+300\n      },\n      []\n    ]\n  }\n]",
        "[{}, {}, {\"emoji \\ud83d\\ude0021\": [{\"\\u0000\\u0001\\u001f11\": false, \"nl\\nhere21\": -1}, {\"back\\\\slash23\": 1e+300}, []], \"long long long long long long long long 26\": [2]}]",
        "[{}, {}, {\"long long long long long long long long 26\": [2], \"emoji 😀21\": [{\"nl\\nhere21\": -1, \"\\u0000\\u0001\\u001f11\": false}, {\"back\\\\slash23\": 1e+300}, []]}]",
    )
    _check(
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
    )
    _check(
        "true",
        "true",
        "true",
        "true",
        "true",
        "true",
    )
    _check(
        "{\"quote\\\"25\": [], \"tab\\there28\": [\"\\u007f del\", null]}",
        "{\"quote\\\"25\": [], \"tab\\there28\": [\"\\u007f del\", null]}",
        "{\"quote\\\"25\":[],\"tab\\there28\":[\"\\u007f del\",null]}",
        "{\n  \"quote\\\"25\": [],\n  \"tab\\there28\": [\n    \"\\u007f del\",\n    null\n  ]\n}",
        "{\"quote\\\"25\": [], \"tab\\there28\": [\"\\u007f del\", null]}",
        "{\"quote\\\"25\": [], \"tab\\there28\": [\"\x7f del\", null]}",
    )
    _check(
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
    )
    _check(
        "null",
        "null",
        "null",
        "null",
        "null",
        "null",
    )


def test_matches_cpython_009() raises:
    _check(
        "[\"日本語\", {\"quote\\\"8\": {\"a15\": null, \"2\": {\"tab\\there11\": 1e-300}, \"a1\": -429905.8839567411}, \"\x7f del0\": [{\"a28\": \"日本語\"}, 533318962720070025, null]}, [-339057.8147886278]]",
        "[\"\\u65e5\\u672c\\u8a9e\", {\"quote\\\"8\": {\"a15\": null, \"2\": {\"tab\\there11\": 1e-300}, \"a1\": -429905.8839567411}, \"\\u007f del0\": [{\"a28\": \"\\u65e5\\u672c\\u8a9e\"}, 533318962720070025, null]}, [-339057.8147886278]]",
        "[\"\\u65e5\\u672c\\u8a9e\",{\"quote\\\"8\":{\"a15\":null,\"2\":{\"tab\\there11\":1e-300},\"a1\":-429905.8839567411},\"\\u007f del0\":[{\"a28\":\"\\u65e5\\u672c\\u8a9e\"},533318962720070025,null]},[-339057.8147886278]]",
        "[\n  \"\\u65e5\\u672c\\u8a9e\",\n  {\n    \"quote\\\"8\": {\n      \"a15\": null,\n      \"2\": {\n        \"tab\\there11\": 1e-300\n      },\n      \"a1\": -429905.8839567411\n    },\n    \"\\u007f del0\": [\n      {\n        \"a28\": \"\\u65e5\\u672c\\u8a9e\"\n      },\n      533318962720070025,\n      null\n    ]\n  },\n  [\n    -339057.8147886278\n  ]\n]",
        "[\"\\u65e5\\u672c\\u8a9e\", {\"quote\\\"8\": {\"2\": {\"tab\\there11\": 1e-300}, \"a1\": -429905.8839567411, \"a15\": null}, \"\\u007f del0\": [{\"a28\": \"\\u65e5\\u672c\\u8a9e\"}, 533318962720070025, null]}, [-339057.8147886278]]",
        "[\"日本語\", {\"quote\\\"8\": {\"a15\": null, \"2\": {\"tab\\there11\": 1e-300}, \"a1\": -429905.8839567411}, \"\x7f del0\": [{\"a28\": \"日本語\"}, 533318962720070025, null]}, [-339057.8147886278]]",
    )
    _check(
        "-756508.0338407161",
        "-756508.0338407161",
        "-756508.0338407161",
        "-756508.0338407161",
        "-756508.0338407161",
        "-756508.0338407161",
    )
    _check(
        "[1e+300, false, []]",
        "[1e+300, false, []]",
        "[1e+300,false,[]]",
        "[\n  1e+300,\n  false,\n  []\n]",
        "[1e+300, false, []]",
        "[1e+300, false, []]",
    )
    _check(
        "{\"tab\\there18\": [[2, [951899.9049590211], []], {}, {\"nl\\nhere12\": [-2719465219843001252], \"a22\": [-9, 726741.4024860503], \"\x7f del10\": []}]}",
        "{\"tab\\there18\": [[2, [951899.9049590211], []], {}, {\"nl\\nhere12\": [-2719465219843001252], \"a22\": [-9, 726741.4024860503], \"\\u007f del10\": []}]}",
        "{\"tab\\there18\":[[2,[951899.9049590211],[]],{},{\"nl\\nhere12\":[-2719465219843001252],\"a22\":[-9,726741.4024860503],\"\\u007f del10\":[]}]}",
        "{\n  \"tab\\there18\": [\n    [\n      2,\n      [\n        951899.9049590211\n      ],\n      []\n    ],\n    {},\n    {\n      \"nl\\nhere12\": [\n        -2719465219843001252\n      ],\n      \"a22\": [\n        -9,\n        726741.4024860503\n      ],\n      \"\\u007f del10\": []\n    }\n  ]\n}",
        "{\"tab\\there18\": [[2, [951899.9049590211], []], {}, {\"a22\": [-9, 726741.4024860503], \"nl\\nhere12\": [-2719465219843001252], \"\\u007f del10\": []}]}",
        "{\"tab\\there18\": [[2, [951899.9049590211], []], {}, {\"nl\\nhere12\": [-2719465219843001252], \"a22\": [-9, 726741.4024860503], \"\x7f del10\": []}]}",
    )
    _check(
        "{\"emoji \\ud83d\\ude0019\": {\"\\u0000\\u0001\\u001f21\": [[677543.4070741541, 0.1, -1]], \"\\u0000\\u0001\\u001f14\": {\"\\u007f del23\": {\"key2\": 1, \"\\u007f del24\": \"back\\\\slash\", \"\\u65e5\\u672c\\u8a9e12\": 3, \"\\u65e5\\u672c\\u8a9e9\": 571812.1838212367}, \"\\u007f del20\": {\"back\\\\slash1\": true, \"\\u65e5\\u672c\\u8a9e29\": 0.3333333333333333, \"nl\\nhere6\": -7}, \"nl\\nhere25\": {\"\\u007f del2\": \"\\u0000\\u0001\\u001f\"}}}, \"key13\": 4}",
        "{\"emoji \\ud83d\\ude0019\": {\"\\u0000\\u0001\\u001f21\": [[677543.4070741541, 0.1, -1]], \"\\u0000\\u0001\\u001f14\": {\"\\u007f del23\": {\"key2\": 1, \"\\u007f del24\": \"back\\\\slash\", \"\\u65e5\\u672c\\u8a9e12\": 3, \"\\u65e5\\u672c\\u8a9e9\": 571812.1838212367}, \"\\u007f del20\": {\"back\\\\slash1\": true, \"\\u65e5\\u672c\\u8a9e29\": 0.3333333333333333, \"nl\\nhere6\": -7}, \"nl\\nhere25\": {\"\\u007f del2\": \"\\u0000\\u0001\\u001f\"}}}, \"key13\": 4}",
        "{\"emoji \\ud83d\\ude0019\":{\"\\u0000\\u0001\\u001f21\":[[677543.4070741541,0.1,-1]],\"\\u0000\\u0001\\u001f14\":{\"\\u007f del23\":{\"key2\":1,\"\\u007f del24\":\"back\\\\slash\",\"\\u65e5\\u672c\\u8a9e12\":3,\"\\u65e5\\u672c\\u8a9e9\":571812.1838212367},\"\\u007f del20\":{\"back\\\\slash1\":true,\"\\u65e5\\u672c\\u8a9e29\":0.3333333333333333,\"nl\\nhere6\":-7},\"nl\\nhere25\":{\"\\u007f del2\":\"\\u0000\\u0001\\u001f\"}}},\"key13\":4}",
        "{\n  \"emoji \\ud83d\\ude0019\": {\n    \"\\u0000\\u0001\\u001f21\": [\n      [\n        677543.4070741541,\n        0.1,\n        -1\n      ]\n    ],\n    \"\\u0000\\u0001\\u001f14\": {\n      \"\\u007f del23\": {\n        \"key2\": 1,\n        \"\\u007f del24\": \"back\\\\slash\",\n        \"\\u65e5\\u672c\\u8a9e12\": 3,\n        \"\\u65e5\\u672c\\u8a9e9\": 571812.1838212367\n      },\n      \"\\u007f del20\": {\n        \"back\\\\slash1\": true,\n        \"\\u65e5\\u672c\\u8a9e29\": 0.3333333333333333,\n        \"nl\\nhere6\": -7\n      },\n      \"nl\\nhere25\": {\n        \"\\u007f del2\": \"\\u0000\\u0001\\u001f\"\n      }\n    }\n  },\n  \"key13\": 4\n}",
        "{\"emoji \\ud83d\\ude0019\": {\"\\u0000\\u0001\\u001f14\": {\"nl\\nhere25\": {\"\\u007f del2\": \"\\u0000\\u0001\\u001f\"}, \"\\u007f del20\": {\"back\\\\slash1\": true, \"nl\\nhere6\": -7, \"\\u65e5\\u672c\\u8a9e29\": 0.3333333333333333}, \"\\u007f del23\": {\"key2\": 1, \"\\u007f del24\": \"back\\\\slash\", \"\\u65e5\\u672c\\u8a9e12\": 3, \"\\u65e5\\u672c\\u8a9e9\": 571812.1838212367}}, \"\\u0000\\u0001\\u001f21\": [[677543.4070741541, 0.1, -1]]}, \"key13\": 4}",
        "{\"emoji 😀19\": {\"\\u0000\\u0001\\u001f21\": [[677543.4070741541, 0.1, -1]], \"\\u0000\\u0001\\u001f14\": {\"\x7f del23\": {\"key2\": 1, \"\x7f del24\": \"back\\\\slash\", \"日本語12\": 3, \"日本語9\": 571812.1838212367}, \"\x7f del20\": {\"back\\\\slash1\": true, \"日本語29\": 0.3333333333333333, \"nl\\nhere6\": -7}, \"nl\\nhere25\": {\"\x7f del2\": \"\\u0000\\u0001\\u001f\"}}}, \"key13\": 4}",
    )
    _check(
        "{\"key28\": true, \"nl\\nhere28\": false, \"key21\": \"\x7f del\"}",
        "{\"key28\": true, \"nl\\nhere28\": false, \"key21\": \"\\u007f del\"}",
        "{\"key28\":true,\"nl\\nhere28\":false,\"key21\":\"\\u007f del\"}",
        "{\n  \"key28\": true,\n  \"nl\\nhere28\": false,\n  \"key21\": \"\\u007f del\"\n}",
        "{\"key21\": \"\\u007f del\", \"key28\": true, \"nl\\nhere28\": false}",
        "{\"key28\": true, \"nl\\nhere28\": false, \"key21\": \"\x7f del\"}",
    )
    _check(
        "122480.71537293913",
        "122480.71537293913",
        "122480.71537293913",
        "122480.71537293913",
        "122480.71537293913",
        "122480.71537293913",
    )
    _check(
        "[{\"emoji 😀29\": 1e-300, \"7\": [null, {\"key0\": null, \"a6\": \"a\", \"nl\\nhere18\": null, \"emoji 😀12\": 4475191748282758876}, \"nl\\nhere\"]}]",
        "[{\"emoji \\ud83d\\ude0029\": 1e-300, \"7\": [null, {\"key0\": null, \"a6\": \"a\", \"nl\\nhere18\": null, \"emoji \\ud83d\\ude0012\": 4475191748282758876}, \"nl\\nhere\"]}]",
        "[{\"emoji \\ud83d\\ude0029\":1e-300,\"7\":[null,{\"key0\":null,\"a6\":\"a\",\"nl\\nhere18\":null,\"emoji \\ud83d\\ude0012\":4475191748282758876},\"nl\\nhere\"]}]",
        "[\n  {\n    \"emoji \\ud83d\\ude0029\": 1e-300,\n    \"7\": [\n      null,\n      {\n        \"key0\": null,\n        \"a6\": \"a\",\n        \"nl\\nhere18\": null,\n        \"emoji \\ud83d\\ude0012\": 4475191748282758876\n      },\n      \"nl\\nhere\"\n    ]\n  }\n]",
        "[{\"7\": [null, {\"a6\": \"a\", \"emoji \\ud83d\\ude0012\": 4475191748282758876, \"key0\": null, \"nl\\nhere18\": null}, \"nl\\nhere\"], \"emoji \\ud83d\\ude0029\": 1e-300}]",
        "[{\"emoji 😀29\": 1e-300, \"7\": [null, {\"key0\": null, \"a6\": \"a\", \"nl\\nhere18\": null, \"emoji 😀12\": 4475191748282758876}, \"nl\\nhere\"]}]",
    )
    _check(
        "{\"key1\": true, \"back\\\\slash11\": [{\"key3\": -936701571152254302, \"a9\": 646206.345621367}, -987919.8567307586, 0.3333333333333333], \"\\u007f del19\": [{\"\\u007f del8\": null, \"emoji \\ud83d\\ude0010\": null}, 1243853621215917917]}",
        "{\"key1\": true, \"back\\\\slash11\": [{\"key3\": -936701571152254302, \"a9\": 646206.345621367}, -987919.8567307586, 0.3333333333333333], \"\\u007f del19\": [{\"\\u007f del8\": null, \"emoji \\ud83d\\ude0010\": null}, 1243853621215917917]}",
        "{\"key1\":true,\"back\\\\slash11\":[{\"key3\":-936701571152254302,\"a9\":646206.345621367},-987919.8567307586,0.3333333333333333],\"\\u007f del19\":[{\"\\u007f del8\":null,\"emoji \\ud83d\\ude0010\":null},1243853621215917917]}",
        "{\n  \"key1\": true,\n  \"back\\\\slash11\": [\n    {\n      \"key3\": -936701571152254302,\n      \"a9\": 646206.345621367\n    },\n    -987919.8567307586,\n    0.3333333333333333\n  ],\n  \"\\u007f del19\": [\n    {\n      \"\\u007f del8\": null,\n      \"emoji \\ud83d\\ude0010\": null\n    },\n    1243853621215917917\n  ]\n}",
        "{\"back\\\\slash11\": [{\"a9\": 646206.345621367, \"key3\": -936701571152254302}, -987919.8567307586, 0.3333333333333333], \"key1\": true, \"\\u007f del19\": [{\"emoji \\ud83d\\ude0010\": null, \"\\u007f del8\": null}, 1243853621215917917]}",
        "{\"key1\": true, \"back\\\\slash11\": [{\"key3\": -936701571152254302, \"a9\": 646206.345621367}, -987919.8567307586, 0.3333333333333333], \"\x7f del19\": [{\"\x7f del8\": null, \"emoji 😀10\": null}, 1243853621215917917]}",
    )
    _check(
        "{}",
        "{}",
        "{}",
        "{}",
        "{}",
        "{}",
    )
    _check(
        "[null, {}, [{}, {\"emoji \\ud83d\\ude003\": null, \"13\": -9}, [2, 0.3333333333333333, false]]]",
        "[null, {}, [{}, {\"emoji \\ud83d\\ude003\": null, \"13\": -9}, [2, 0.3333333333333333, false]]]",
        "[null,{},[{},{\"emoji \\ud83d\\ude003\":null,\"13\":-9},[2,0.3333333333333333,false]]]",
        "[\n  null,\n  {},\n  [\n    {},\n    {\n      \"emoji \\ud83d\\ude003\": null,\n      \"13\": -9\n    },\n    [\n      2,\n      0.3333333333333333,\n      false\n    ]\n  ]\n]",
        "[null, {}, [{}, {\"13\": -9, \"emoji \\ud83d\\ude003\": null}, [2, 0.3333333333333333, false]]]",
        "[null, {}, [{}, {\"emoji 😀3\": null, \"13\": -9}, [2, 0.3333333333333333, false]]]",
    )
    _check(
        "{}",
        "{}",
        "{}",
        "{}",
        "{}",
        "{}",
    )


def test_matches_cpython_010() raises:
    _check(
        "true",
        "true",
        "true",
        "true",
        "true",
        "true",
    )
    _check(
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
    )
    _check(
        "[[], [[{\"\x7f del29\": \"\", \"key15\": true, \"emoji 😀10\": \"back\\\\slash\"}, -3961204585688987771, [1, 1e-300, \"nl\\nhere\"]], -0.0, \"\\u0000\\u0001\\u001f\"]]",
        "[[], [[{\"\\u007f del29\": \"\", \"key15\": true, \"emoji \\ud83d\\ude0010\": \"back\\\\slash\"}, -3961204585688987771, [1, 1e-300, \"nl\\nhere\"]], -0.0, \"\\u0000\\u0001\\u001f\"]]",
        "[[],[[{\"\\u007f del29\":\"\",\"key15\":true,\"emoji \\ud83d\\ude0010\":\"back\\\\slash\"},-3961204585688987771,[1,1e-300,\"nl\\nhere\"]],-0.0,\"\\u0000\\u0001\\u001f\"]]",
        "[\n  [],\n  [\n    [\n      {\n        \"\\u007f del29\": \"\",\n        \"key15\": true,\n        \"emoji \\ud83d\\ude0010\": \"back\\\\slash\"\n      },\n      -3961204585688987771,\n      [\n        1,\n        1e-300,\n        \"nl\\nhere\"\n      ]\n    ],\n    -0.0,\n    \"\\u0000\\u0001\\u001f\"\n  ]\n]",
        "[[], [[{\"emoji \\ud83d\\ude0010\": \"back\\\\slash\", \"key15\": true, \"\\u007f del29\": \"\"}, -3961204585688987771, [1, 1e-300, \"nl\\nhere\"]], -0.0, \"\\u0000\\u0001\\u001f\"]]",
        "[[], [[{\"\x7f del29\": \"\", \"key15\": true, \"emoji 😀10\": \"back\\\\slash\"}, -3961204585688987771, [1, 1e-300, \"nl\\nhere\"]], -0.0, \"\\u0000\\u0001\\u001f\"]]",
    )
    _check(
        "{\"emoji \\ud83d\\ude0022\": 2, \"back\\\\slash14\": [[[0.0, 5, true], null, [null]], true, \"\\u007f del\"]}",
        "{\"emoji \\ud83d\\ude0022\": 2, \"back\\\\slash14\": [[[0.0, 5, true], null, [null]], true, \"\\u007f del\"]}",
        "{\"emoji \\ud83d\\ude0022\":2,\"back\\\\slash14\":[[[0.0,5,true],null,[null]],true,\"\\u007f del\"]}",
        "{\n  \"emoji \\ud83d\\ude0022\": 2,\n  \"back\\\\slash14\": [\n    [\n      [\n        0.0,\n        5,\n        true\n      ],\n      null,\n      [\n        null\n      ]\n    ],\n    true,\n    \"\\u007f del\"\n  ]\n}",
        "{\"back\\\\slash14\": [[[0.0, 5, true], null, [null]], true, \"\\u007f del\"], \"emoji \\ud83d\\ude0022\": 2}",
        "{\"emoji 😀22\": 2, \"back\\\\slash14\": [[[0.0, 5, true], null, [null]], true, \"\x7f del\"]}",
    )
    _check(
        "false",
        "false",
        "false",
        "false",
        "false",
        "false",
    )
    _check(
        "[[null, [[], true, 6]]]",
        "[[null, [[], true, 6]]]",
        "[[null,[[],true,6]]]",
        "[\n  [\n    null,\n    [\n      [],\n      true,\n      6\n    ]\n  ]\n]",
        "[[null, [[], true, 6]]]",
        "[[null, [[], true, 6]]]",
    )
    _check(
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
    )
    _check(
        "[-799073.3451386772, 575031.7250018602]",
        "[-799073.3451386772, 575031.7250018602]",
        "[-799073.3451386772,575031.7250018602]",
        "[\n  -799073.3451386772,\n  575031.7250018602\n]",
        "[-799073.3451386772, 575031.7250018602]",
        "[-799073.3451386772, 575031.7250018602]",
    )
    _check(
        "null",
        "null",
        "null",
        "null",
        "null",
        "null",
    )
    _check(
        "false",
        "false",
        "false",
        "false",
        "false",
        "false",
    )
    _check(
        "[-952373.7719781189, -0.0, {\"emoji \\ud83d\\ude0014\": [false]}]",
        "[-952373.7719781189, -0.0, {\"emoji \\ud83d\\ude0014\": [false]}]",
        "[-952373.7719781189,-0.0,{\"emoji \\ud83d\\ude0014\":[false]}]",
        "[\n  -952373.7719781189,\n  -0.0,\n  {\n    \"emoji \\ud83d\\ude0014\": [\n      false\n    ]\n  }\n]",
        "[-952373.7719781189, -0.0, {\"emoji \\ud83d\\ude0014\": [false]}]",
        "[-952373.7719781189, -0.0, {\"emoji 😀14\": [false]}]",
    )
    _check(
        "{\"quote\\\"19\": {\"日本語11\": -8}}",
        "{\"quote\\\"19\": {\"\\u65e5\\u672c\\u8a9e11\": -8}}",
        "{\"quote\\\"19\":{\"\\u65e5\\u672c\\u8a9e11\":-8}}",
        "{\n  \"quote\\\"19\": {\n    \"\\u65e5\\u672c\\u8a9e11\": -8\n  }\n}",
        "{\"quote\\\"19\": {\"\\u65e5\\u672c\\u8a9e11\": -8}}",
        "{\"quote\\\"19\": {\"日本語11\": -8}}",
    )


def test_matches_cpython_011() raises:
    _check(
        "{\"back\\\\slash3\": {\"\\u0000\\u0001\\u001f24\": {\"key7\": {\"quote\\\"1\": -0.0, \"\\u0000\\u0001\\u001f26\": \"\", \"quote\\\"17\": \"\\u0000\\u0001\\u001f\", \"\\u65e5\\u672c\\u8a9e8\": false}, \"11\": null, \"\\u65e5\\u672c\\u8a9e19\": 0.0}, \"\\u65e5\\u672c\\u8a9e26\": {\"long long long long long long long long 26\": []}, \"emoji \\ud83d\\ude0018\": {\"\\u0000\\u0001\\u001f9\": 0.3333333333333333, \"emoji \\ud83d\\ude000\": {\"quote\\\"4\": null, \"quote\\\"9\": false, \"quote\\\"19\": \"quote\\\"\"}, \"0\": true}}, \"back\\\\slash25\": false, \"nl\\nhere18\": 990541.9011066682}",
        "{\"back\\\\slash3\": {\"\\u0000\\u0001\\u001f24\": {\"key7\": {\"quote\\\"1\": -0.0, \"\\u0000\\u0001\\u001f26\": \"\", \"quote\\\"17\": \"\\u0000\\u0001\\u001f\", \"\\u65e5\\u672c\\u8a9e8\": false}, \"11\": null, \"\\u65e5\\u672c\\u8a9e19\": 0.0}, \"\\u65e5\\u672c\\u8a9e26\": {\"long long long long long long long long 26\": []}, \"emoji \\ud83d\\ude0018\": {\"\\u0000\\u0001\\u001f9\": 0.3333333333333333, \"emoji \\ud83d\\ude000\": {\"quote\\\"4\": null, \"quote\\\"9\": false, \"quote\\\"19\": \"quote\\\"\"}, \"0\": true}}, \"back\\\\slash25\": false, \"nl\\nhere18\": 990541.9011066682}",
        "{\"back\\\\slash3\":{\"\\u0000\\u0001\\u001f24\":{\"key7\":{\"quote\\\"1\":-0.0,\"\\u0000\\u0001\\u001f26\":\"\",\"quote\\\"17\":\"\\u0000\\u0001\\u001f\",\"\\u65e5\\u672c\\u8a9e8\":false},\"11\":null,\"\\u65e5\\u672c\\u8a9e19\":0.0},\"\\u65e5\\u672c\\u8a9e26\":{\"long long long long long long long long 26\":[]},\"emoji \\ud83d\\ude0018\":{\"\\u0000\\u0001\\u001f9\":0.3333333333333333,\"emoji \\ud83d\\ude000\":{\"quote\\\"4\":null,\"quote\\\"9\":false,\"quote\\\"19\":\"quote\\\"\"},\"0\":true}},\"back\\\\slash25\":false,\"nl\\nhere18\":990541.9011066682}",
        "{\n  \"back\\\\slash3\": {\n    \"\\u0000\\u0001\\u001f24\": {\n      \"key7\": {\n        \"quote\\\"1\": -0.0,\n        \"\\u0000\\u0001\\u001f26\": \"\",\n        \"quote\\\"17\": \"\\u0000\\u0001\\u001f\",\n        \"\\u65e5\\u672c\\u8a9e8\": false\n      },\n      \"11\": null,\n      \"\\u65e5\\u672c\\u8a9e19\": 0.0\n    },\n    \"\\u65e5\\u672c\\u8a9e26\": {\n      \"long long long long long long long long 26\": []\n    },\n    \"emoji \\ud83d\\ude0018\": {\n      \"\\u0000\\u0001\\u001f9\": 0.3333333333333333,\n      \"emoji \\ud83d\\ude000\": {\n        \"quote\\\"4\": null,\n        \"quote\\\"9\": false,\n        \"quote\\\"19\": \"quote\\\"\"\n      },\n      \"0\": true\n    }\n  },\n  \"back\\\\slash25\": false,\n  \"nl\\nhere18\": 990541.9011066682\n}",
        "{\"back\\\\slash25\": false, \"back\\\\slash3\": {\"\\u0000\\u0001\\u001f24\": {\"11\": null, \"key7\": {\"\\u0000\\u0001\\u001f26\": \"\", \"quote\\\"1\": -0.0, \"quote\\\"17\": \"\\u0000\\u0001\\u001f\", \"\\u65e5\\u672c\\u8a9e8\": false}, \"\\u65e5\\u672c\\u8a9e19\": 0.0}, \"emoji \\ud83d\\ude0018\": {\"\\u0000\\u0001\\u001f9\": 0.3333333333333333, \"0\": true, \"emoji \\ud83d\\ude000\": {\"quote\\\"19\": \"quote\\\"\", \"quote\\\"4\": null, \"quote\\\"9\": false}}, \"\\u65e5\\u672c\\u8a9e26\": {\"long long long long long long long long 26\": []}}, \"nl\\nhere18\": 990541.9011066682}",
        "{\"back\\\\slash3\": {\"\\u0000\\u0001\\u001f24\": {\"key7\": {\"quote\\\"1\": -0.0, \"\\u0000\\u0001\\u001f26\": \"\", \"quote\\\"17\": \"\\u0000\\u0001\\u001f\", \"日本語8\": false}, \"11\": null, \"日本語19\": 0.0}, \"日本語26\": {\"long long long long long long long long 26\": []}, \"emoji 😀18\": {\"\\u0000\\u0001\\u001f9\": 0.3333333333333333, \"emoji 😀0\": {\"quote\\\"4\": null, \"quote\\\"9\": false, \"quote\\\"19\": \"quote\\\"\"}, \"0\": true}}, \"back\\\\slash25\": false, \"nl\\nhere18\": 990541.9011066682}",
    )
    _check(
        "[2028879686050696871]",
        "[2028879686050696871]",
        "[2028879686050696871]",
        "[\n  2028879686050696871\n]",
        "[2028879686050696871]",
        "[2028879686050696871]",
    )
    _check(
        "null",
        "null",
        "null",
        "null",
        "null",
        "null",
    )
    _check(
        "{\"日本語10\": \"long long long long long long long long \", \"日本語5\": 1e+300, \"emoji 😀13\": -1435226709037074625}",
        "{\"\\u65e5\\u672c\\u8a9e10\": \"long long long long long long long long \", \"\\u65e5\\u672c\\u8a9e5\": 1e+300, \"emoji \\ud83d\\ude0013\": -1435226709037074625}",
        "{\"\\u65e5\\u672c\\u8a9e10\":\"long long long long long long long long \",\"\\u65e5\\u672c\\u8a9e5\":1e+300,\"emoji \\ud83d\\ude0013\":-1435226709037074625}",
        "{\n  \"\\u65e5\\u672c\\u8a9e10\": \"long long long long long long long long \",\n  \"\\u65e5\\u672c\\u8a9e5\": 1e+300,\n  \"emoji \\ud83d\\ude0013\": -1435226709037074625\n}",
        "{\"emoji \\ud83d\\ude0013\": -1435226709037074625, \"\\u65e5\\u672c\\u8a9e10\": \"long long long long long long long long \", \"\\u65e5\\u672c\\u8a9e5\": 1e+300}",
        "{\"日本語10\": \"long long long long long long long long \", \"日本語5\": 1e+300, \"emoji 😀13\": -1435226709037074625}",
    )
    _check(
        "[[false, [{\"28\": 688617.7981077302, \"\\u007f del8\": \"\\u65e5\\u672c\\u8a9e\"}], {}], {}, 2]",
        "[[false, [{\"28\": 688617.7981077302, \"\\u007f del8\": \"\\u65e5\\u672c\\u8a9e\"}], {}], {}, 2]",
        "[[false,[{\"28\":688617.7981077302,\"\\u007f del8\":\"\\u65e5\\u672c\\u8a9e\"}],{}],{},2]",
        "[\n  [\n    false,\n    [\n      {\n        \"28\": 688617.7981077302,\n        \"\\u007f del8\": \"\\u65e5\\u672c\\u8a9e\"\n      }\n    ],\n    {}\n  ],\n  {},\n  2\n]",
        "[[false, [{\"28\": 688617.7981077302, \"\\u007f del8\": \"\\u65e5\\u672c\\u8a9e\"}], {}], {}, 2]",
        "[[false, [{\"28\": 688617.7981077302, \"\x7f del8\": \"日本語\"}], {}], {}, 2]",
    )
    _check(
        "\"\"",
        "\"\"",
        "\"\"",
        "\"\"",
        "\"\"",
        "\"\"",
    )
    _check(
        "[0.1]",
        "[0.1]",
        "[0.1]",
        "[\n  0.1\n]",
        "[0.1]",
        "[0.1]",
    )
    _check(
        "{\"long long long long long long long long 16\": false, \"back\\\\slash5\": {\"quote\\\"14\": [{\"long long long long long long long long 15\": null, \"\\u65e5\\u672c\\u8a9e11\": 960060.883783038}, {}, []], \"\\u007f del6\": null, \"back\\\\slash16\": [[false, 0.0]]}, \"key5\": {\"a15\": -0.0, \"\\u0000\\u0001\\u001f28\": {\"tab\\there19\": [false], \"\\u0000\\u0001\\u001f17\": false, \"tab\\there0\": \"key\", \"quote\\\"10\": {}}, \"a1\": 630561.4036809495}, \"tab\\there26\": {\"\\u65e5\\u672c\\u8a9e25\": [{\"long long long long long long long long 23\": -9, \"back\\\\slash14\": 1e-300, \"quote\\\"23\": -604575.4078206298}], \"\\u0000\\u0001\\u001f24\": -203312.21907736768, \"long long long long long long long long 2\": [{\"\\u007f del3\": null, \"long long long long long long long long 6\": \"emoji \\ud83d\\ude00\", \"quote\\\"5\": -971129.1729292517, \"back\\\\slash10\": 1e-300}, null]}}",
        "{\"long long long long long long long long 16\": false, \"back\\\\slash5\": {\"quote\\\"14\": [{\"long long long long long long long long 15\": null, \"\\u65e5\\u672c\\u8a9e11\": 960060.883783038}, {}, []], \"\\u007f del6\": null, \"back\\\\slash16\": [[false, 0.0]]}, \"key5\": {\"a15\": -0.0, \"\\u0000\\u0001\\u001f28\": {\"tab\\there19\": [false], \"\\u0000\\u0001\\u001f17\": false, \"tab\\there0\": \"key\", \"quote\\\"10\": {}}, \"a1\": 630561.4036809495}, \"tab\\there26\": {\"\\u65e5\\u672c\\u8a9e25\": [{\"long long long long long long long long 23\": -9, \"back\\\\slash14\": 1e-300, \"quote\\\"23\": -604575.4078206298}], \"\\u0000\\u0001\\u001f24\": -203312.21907736768, \"long long long long long long long long 2\": [{\"\\u007f del3\": null, \"long long long long long long long long 6\": \"emoji \\ud83d\\ude00\", \"quote\\\"5\": -971129.1729292517, \"back\\\\slash10\": 1e-300}, null]}}",
        "{\"long long long long long long long long 16\":false,\"back\\\\slash5\":{\"quote\\\"14\":[{\"long long long long long long long long 15\":null,\"\\u65e5\\u672c\\u8a9e11\":960060.883783038},{},[]],\"\\u007f del6\":null,\"back\\\\slash16\":[[false,0.0]]},\"key5\":{\"a15\":-0.0,\"\\u0000\\u0001\\u001f28\":{\"tab\\there19\":[false],\"\\u0000\\u0001\\u001f17\":false,\"tab\\there0\":\"key\",\"quote\\\"10\":{}},\"a1\":630561.4036809495},\"tab\\there26\":{\"\\u65e5\\u672c\\u8a9e25\":[{\"long long long long long long long long 23\":-9,\"back\\\\slash14\":1e-300,\"quote\\\"23\":-604575.4078206298}],\"\\u0000\\u0001\\u001f24\":-203312.21907736768,\"long long long long long long long long 2\":[{\"\\u007f del3\":null,\"long long long long long long long long 6\":\"emoji \\ud83d\\ude00\",\"quote\\\"5\":-971129.1729292517,\"back\\\\slash10\":1e-300},null]}}",
        "{\n  \"long long long long long long long long 16\": false,\n  \"back\\\\slash5\": {\n    \"quote\\\"14\": [\n      {\n        \"long long long long long long long long 15\": null,\n        \"\\u65e5\\u672c\\u8a9e11\": 960060.883783038\n      },\n      {},\n      []\n    ],\n    \"\\u007f del6\": null,\n    \"back\\\\slash16\": [\n      [\n        false,\n        0.0\n      ]\n    ]\n  },\n  \"key5\": {\n    \"a15\": -0.0,\n    \"\\u0000\\u0001\\u001f28\": {\n      \"tab\\there19\": [\n        false\n      ],\n      \"\\u0000\\u0001\\u001f17\": false,\n      \"tab\\there0\": \"key\",\n      \"quote\\\"10\": {}\n    },\n    \"a1\": 630561.4036809495\n  },\n  \"tab\\there26\": {\n    \"\\u65e5\\u672c\\u8a9e25\": [\n      {\n        \"long long long long long long long long 23\": -9,\n        \"back\\\\slash14\": 1e-300,\n        \"quote\\\"23\": -604575.4078206298\n      }\n    ],\n    \"\\u0000\\u0001\\u001f24\": -203312.21907736768,\n    \"long long long long long long long long 2\": [\n      {\n        \"\\u007f del3\": null,\n        \"long long long long long long long long 6\": \"emoji \\ud83d\\ude00\",\n        \"quote\\\"5\": -971129.1729292517,\n        \"back\\\\slash10\": 1e-300\n      },\n      null\n    ]\n  }\n}",
        "{\"back\\\\slash5\": {\"back\\\\slash16\": [[false, 0.0]], \"quote\\\"14\": [{\"long long long long long long long long 15\": null, \"\\u65e5\\u672c\\u8a9e11\": 960060.883783038}, {}, []], \"\\u007f del6\": null}, \"key5\": {\"\\u0000\\u0001\\u001f28\": {\"\\u0000\\u0001\\u001f17\": false, \"quote\\\"10\": {}, \"tab\\there0\": \"key\", \"tab\\there19\": [false]}, \"a1\": 630561.4036809495, \"a15\": -0.0}, \"long long long long long long long long 16\": false, \"tab\\there26\": {\"\\u0000\\u0001\\u001f24\": -203312.21907736768, \"long long long long long long long long 2\": [{\"back\\\\slash10\": 1e-300, \"long long long long long long long long 6\": \"emoji \\ud83d\\ude00\", \"quote\\\"5\": -971129.1729292517, \"\\u007f del3\": null}, null], \"\\u65e5\\u672c\\u8a9e25\": [{\"back\\\\slash14\": 1e-300, \"long long long long long long long long 23\": -9, \"quote\\\"23\": -604575.4078206298}]}}",
        "{\"long long long long long long long long 16\": false, \"back\\\\slash5\": {\"quote\\\"14\": [{\"long long long long long long long long 15\": null, \"日本語11\": 960060.883783038}, {}, []], \"\x7f del6\": null, \"back\\\\slash16\": [[false, 0.0]]}, \"key5\": {\"a15\": -0.0, \"\\u0000\\u0001\\u001f28\": {\"tab\\there19\": [false], \"\\u0000\\u0001\\u001f17\": false, \"tab\\there0\": \"key\", \"quote\\\"10\": {}}, \"a1\": 630561.4036809495}, \"tab\\there26\": {\"日本語25\": [{\"long long long long long long long long 23\": -9, \"back\\\\slash14\": 1e-300, \"quote\\\"23\": -604575.4078206298}], \"\\u0000\\u0001\\u001f24\": -203312.21907736768, \"long long long long long long long long 2\": [{\"\x7f del3\": null, \"long long long long long long long long 6\": \"emoji 😀\", \"quote\\\"5\": -971129.1729292517, \"back\\\\slash10\": 1e-300}, null]}}",
    )
    _check(
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
    )
    _check(
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
    )
    _check(
        "[{\"key27\": 0.0, \"long long long long long long long long 0\": [{\"back\\\\slash8\": 0.3333333333333333}, 1e+300, []], \"15\": 708135474965777315}, 2958082157651881086]",
        "[{\"key27\": 0.0, \"long long long long long long long long 0\": [{\"back\\\\slash8\": 0.3333333333333333}, 1e+300, []], \"15\": 708135474965777315}, 2958082157651881086]",
        "[{\"key27\":0.0,\"long long long long long long long long 0\":[{\"back\\\\slash8\":0.3333333333333333},1e+300,[]],\"15\":708135474965777315},2958082157651881086]",
        "[\n  {\n    \"key27\": 0.0,\n    \"long long long long long long long long 0\": [\n      {\n        \"back\\\\slash8\": 0.3333333333333333\n      },\n      1e+300,\n      []\n    ],\n    \"15\": 708135474965777315\n  },\n  2958082157651881086\n]",
        "[{\"15\": 708135474965777315, \"key27\": 0.0, \"long long long long long long long long 0\": [{\"back\\\\slash8\": 0.3333333333333333}, 1e+300, []]}, 2958082157651881086]",
        "[{\"key27\": 0.0, \"long long long long long long long long 0\": [{\"back\\\\slash8\": 0.3333333333333333}, 1e+300, []], \"15\": 708135474965777315}, 2958082157651881086]",
    )
    _check(
        "-2992847682851861837",
        "-2992847682851861837",
        "-2992847682851861837",
        "-2992847682851861837",
        "-2992847682851861837",
        "-2992847682851861837",
    )


def test_matches_cpython_012() raises:
    _check(
        "1e+300",
        "1e+300",
        "1e+300",
        "1e+300",
        "1e+300",
        "1e+300",
    )
    _check(
        "3014810473789228556",
        "3014810473789228556",
        "3014810473789228556",
        "3014810473789228556",
        "3014810473789228556",
        "3014810473789228556",
    )
    _check(
        "[[2, 431584.4868337519, []], 0.3333333333333333]",
        "[[2, 431584.4868337519, []], 0.3333333333333333]",
        "[[2,431584.4868337519,[]],0.3333333333333333]",
        "[\n  [\n    2,\n    431584.4868337519,\n    []\n  ],\n  0.3333333333333333\n]",
        "[[2, 431584.4868337519, []], 0.3333333333333333]",
        "[[2, 431584.4868337519, []], 0.3333333333333333]",
    )
    _check(
        "{}",
        "{}",
        "{}",
        "{}",
        "{}",
        "{}",
    )
    _check(
        "null",
        "null",
        "null",
        "null",
        "null",
        "null",
    )
    _check(
        "-9",
        "-9",
        "-9",
        "-9",
        "-9",
        "-9",
    )
    _check(
        "{\"nl\\nhere18\": \"long long long long long long long long \", \"back\\\\slash1\": [[-542634.8751090267, [-269419601100002088], {\"key25\": true, \"long long long long long long long long 21\": false, \"nl\\nhere7\": 9}], [-2250471023367825234]]}",
        "{\"nl\\nhere18\": \"long long long long long long long long \", \"back\\\\slash1\": [[-542634.8751090267, [-269419601100002088], {\"key25\": true, \"long long long long long long long long 21\": false, \"nl\\nhere7\": 9}], [-2250471023367825234]]}",
        "{\"nl\\nhere18\":\"long long long long long long long long \",\"back\\\\slash1\":[[-542634.8751090267,[-269419601100002088],{\"key25\":true,\"long long long long long long long long 21\":false,\"nl\\nhere7\":9}],[-2250471023367825234]]}",
        "{\n  \"nl\\nhere18\": \"long long long long long long long long \",\n  \"back\\\\slash1\": [\n    [\n      -542634.8751090267,\n      [\n        -269419601100002088\n      ],\n      {\n        \"key25\": true,\n        \"long long long long long long long long 21\": false,\n        \"nl\\nhere7\": 9\n      }\n    ],\n    [\n      -2250471023367825234\n    ]\n  ]\n}",
        "{\"back\\\\slash1\": [[-542634.8751090267, [-269419601100002088], {\"key25\": true, \"long long long long long long long long 21\": false, \"nl\\nhere7\": 9}], [-2250471023367825234]], \"nl\\nhere18\": \"long long long long long long long long \"}",
        "{\"nl\\nhere18\": \"long long long long long long long long \", \"back\\\\slash1\": [[-542634.8751090267, [-269419601100002088], {\"key25\": true, \"long long long long long long long long 21\": false, \"nl\\nhere7\": 9}], [-2250471023367825234]]}",
    )
    _check(
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
        "[]",
    )
    _check(
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
        "\"back\\\\slash\"",
    )
    _check(
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
    )


def test_rejects_like_cpython_000() raises:
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads("")
    with assert_raises(contains="Expecting value: line 1 column 4 (char 3)"):
        _ = loads("   ")
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads("x")
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads("'a'")
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads("nul")
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads("tru")
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads("fals")
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads("nan")
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads("inf")
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads("-")
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads("+1")
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads(".1")


def test_rejects_like_cpython_001() raises:
    with assert_raises(contains="Extra data: line 1 column 2 (char 1)"):
        _ = loads("1.")
    with assert_raises(contains="Extra data: line 1 column 2 (char 1)"):
        _ = loads("1e")
    with assert_raises(contains="Extra data: line 1 column 2 (char 1)"):
        _ = loads("1e+")
    with assert_raises(contains="Extra data: line 1 column 2 (char 1)"):
        _ = loads("01")
    with assert_raises(contains="Extra data: line 1 column 2 (char 1)"):
        _ = loads("00")
    with assert_raises(contains="Extra data: line 1 column 3 (char 2)"):
        _ = loads("-01")
    with assert_raises(contains="Expecting value: line 1 column 2 (char 1)"):
        _ = loads("[")
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads("]")
    with assert_raises(contains="Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"):
        _ = loads("{")
    with assert_raises(contains="Expecting value: line 1 column 1 (char 0)"):
        _ = loads("}")
    with assert_raises(contains="Expecting value: line 1 column 2 (char 1)"):
        _ = loads("[,]")
    with assert_raises(contains="Expecting value: line 1 column 4 (char 3)"):
        _ = loads("[1,]")


def test_rejects_like_cpython_002() raises:
    with assert_raises(contains="Expecting ',' delimiter: line 1 column 4 (char 3)"):
        _ = loads("[1 2]")
    with assert_raises(contains="Expecting ',' delimiter: line 1 column 5 (char 4)"):
        _ = loads("[1,2")
    with assert_raises(contains="Expecting ',' delimiter: line 1 column 3 (char 2)"):
        _ = loads("[1;2]")
    with assert_raises(contains="Expecting ':' delimiter: line 1 column 5 (char 4)"):
        _ = loads("{\"a\"")
    with assert_raises(contains="Expecting value: line 1 column 6 (char 5)"):
        _ = loads("{\"a\":}")
    with assert_raises(contains="Expecting property name enclosed in double quotes: line 1 column 8 (char 7)"):
        _ = loads("{\"a\":1,}")
    with assert_raises(contains="Expecting ':' delimiter: line 1 column 6 (char 5)"):
        _ = loads("{\"a\" 1}")
    with assert_raises(contains="Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"):
        _ = loads("{1:2}")
    with assert_raises(contains="Expecting ',' delimiter: line 1 column 7 (char 6)"):
        _ = loads("{\"a\":1")
    with assert_raises(contains="Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"):
        _ = loads("{,}")
    with assert_raises(contains="Unterminated string starting at: line 1 column 1 (char 0)"):
        _ = loads("\"abc")
    with assert_raises(contains="Invalid control character at: line 1 column 3 (char 2)"):
        _ = loads("\"a\nb\"")


def test_rejects_like_cpython_003() raises:
    with assert_raises(contains="Invalid \\escape: line 1 column 3 (char 2)"):
        _ = loads("\"a\\qb\"")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 3 (char 2)"):
        _ = loads("\"\\u12\"")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 3 (char 2)"):
        _ = loads("\"\\uZZZZ\"")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 3 (char 2)"):
        _ = loads("\"\\u\"")
    with assert_raises(contains="Unterminated string starting at: line 1 column 1 (char 0)"):
        _ = loads("\"\\\"")
    with assert_raises(contains="Extra data: line 1 column 5 (char 4)"):
        _ = loads("[1] 2")
    with assert_raises(contains="Extra data: line 1 column 9 (char 8)"):
        _ = loads("{\"a\":1} {}")
    with assert_raises(contains="Extra data: line 1 column 3 (char 2)"):
        _ = loads("1 2")
    with assert_raises(contains="Extra data: line 1 column 5 (char 4)"):
        _ = loads("truefalse")
    with assert_raises(contains="Extra data: line 1 column 11 (char 10)"):
        _ = loads("[[1],[2]] trailing")
    with assert_raises(contains="Expecting value: line 1 column 11 (char 10)"):
        _ = loads("{\"outer\": ")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 17 (char 16)"):
        _ = loads("\"a string with \\u0041")


def test_rejects_like_cpython_004() raises:
    with assert_raises(contains="Expecting value: line 1 column 6 (char 5)"):
        _ = loads("{\"a\":")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 4 (char 3)"):
        _ = loads("[\"\\ud83")
    with assert_raises(contains="Unterminated string starting at: line 1 column 2 (char 1)"):
        _ = loads("{\"ou")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 10 (char 9)"):
        _ = loads("[\"\\ud83d\\ude00")
    with assert_raises(contains="Expecting value: line 1 column 7 (char 6)"):
        _ = loads("{\"a\": ")
    with assert_raises(contains="Unterminated string starting at: line 1 column 1 (char 0)"):
        _ = loads("\"a string with")
    with assert_raises(contains="Unterminated string starting at: line 1 column 15 (char 14)"):
        _ = loads("{\"a\": [1, 2, {\"b")
    with assert_raises(contains="Unterminated string starting at: line 1 column 33 (char 32)"):
        _ = loads("{\"a\": [1, 2, {\"b\": null}], \"c\": \"tex")
    with assert_raises(contains="Unterminated string starting at: line 1 column 1 (char 0)"):
        _ = loads("\"a")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 4 (char 3)"):
        _ = loads("[\"\\ud83d")
    with assert_raises(contains="Expecting value: line 1 column 22 (char 21)"):
        _ = loads("[1, 2.5, true, null, ")
    with assert_raises(contains="Expecting value: line 1 column 39 (char 38)"):
        _ = loads("{\"a\": 1e10, \"b\": -2.5e-3, \"c\": [true, ")


def test_rejects_like_cpython_005() raises:
    with assert_raises(contains="Unterminated string starting at: line 1 column 33 (char 32)"):
        _ = loads("{\"a\": [1, 2, {\"b\": null}], \"c\": \"text")
    with assert_raises(contains="Expecting value: line 1 column 27 (char 26)"):
        _ = loads("[\"\\ud83d\\ude00\", \"\\u00e9\",")
    with assert_raises(contains="Unterminated string starting at: line 1 column 15 (char 14)"):
        _ = loads("{\"a\": [1, 2, {\"")
    with assert_raises(contains="Unterminated string starting at: line 1 column 33 (char 32)"):
        _ = loads("{\"a\": [1, 2, {\"b\": null}], \"c\": \"tex")
    with assert_raises(contains="Expecting value: line 1 column 10 (char 9)"):
        _ = loads("[1, 2.5, t")
    with assert_raises(contains="Unterminated string starting at: line 1 column 1 (char 0)"):
        _ = loads("\"a st")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 4 (char 3)"):
        _ = loads("[\"\\ud83d")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 20 (char 19)"):
        _ = loads("[\"\\ud83d\\ude00\", \"\\u")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 10 (char 9)"):
        _ = loads("[\"\\ud83d\\ude")
    with assert_raises(contains="Expecting ',' delimiter: line 1 column 39 (char 38)"):
        _ = loads("{\"a\": [1, 2, {\"b\": null}], \"c\": \"text\"")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 10 (char 9)"):
        _ = loads("[\"\\ud83d\\ude0")
    with assert_raises(contains="Unterminated string starting at: line 1 column 2 (char 1)"):
        _ = loads("{\"outer")


def test_rejects_like_cpython_006() raises:
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 4 (char 3)"):
        _ = loads("[\"\\ud")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 4 (char 3)"):
        _ = loads("[\"\\u")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 10 (char 9)"):
        _ = loads("[\"\\ud83d\\ude00")
    with assert_raises(contains="Unterminated string starting at: line 1 column 1 (char 0)"):
        _ = loads("\"a string with \\u0041 ")
    with assert_raises(contains="Unterminated string starting at: line 1 column 28 (char 27)"):
        _ = loads("[\"\\ud83d\\ude00\", \"\\u00e9\", \"")
    with assert_raises(contains="Expecting ',' delimiter: line 1 column 31 (char 30)"):
        _ = loads("{\"outer\": {\"inner\": [1, [2, [3")
    with assert_raises(contains="Unterminated string starting at: line 1 column 28 (char 27)"):
        _ = loads("[\"\\ud83d\\ude00\", \"\\u00e9\", \"pl")
    with assert_raises(contains="Expecting value: line 1 column 21 (char 20)"):
        _ = loads("{\"outer\": {\"inner\": ")
    with assert_raises(contains="Expecting value: line 1 column 27 (char 26)"):
        _ = loads("[1, 2.5, true, null, {\"k\":")
    with assert_raises(contains="Unterminated string starting at: line 1 column 23 (char 22)"):
        _ = loads("[1, 2.5, true, null, {\"")
    with assert_raises(contains="Expecting value: line 1 column 4 (char 3)"):
        _ = loads("[1,")
    with assert_raises(contains="Invalid \\uXXXX escape: line 1 column 20 (char 19)"):
        _ = loads("[\"\\ud83d\\ude00\", \"\\u")


def test_rejects_like_cpython_007() raises:
    with assert_raises(contains="Unterminated string starting at: line 1 column 28 (char 27)"):
        _ = loads("[\"\\ud83d\\ude00\", \"\\u00e9\", \"plai")
    with assert_raises(contains="Expecting value: line 1 column 30 (char 29)"):
        _ = loads("{\"outer\": {\"inner\": [1, [2, [")


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
