"""Differential tests against PyYAML.

Generated by `scripts/gen_yaml_compat_cases.py`, which runs every case
through PyYAML and records what it produced. Do not edit by hand; add
cases to the generator and re-run it.
"""

from std.testing import TestSuite, assert_equal, assert_raises

from json import dumps
from yaml import safe_dump, safe_load


def _check(text: StringSlice, loaded: StringSlice, dumped: StringSlice) raises:
    """Checks one document against PyYAML.

    Args:
        text: The document to load.
        loaded: What `yaml.safe_load` produced, as compact JSON.
        dumped: What `yaml.safe_dump` produced for that value.

    Raises:
        If loading or dumping differs from PyYAML.
    """
    var doc = safe_load(text)
    assert_equal(dumps(doc, separators=(",", ":")), loaded, String(text))
    assert_equal(safe_dump(doc), dumped, String(text))


def test_matches_pyyaml_000() raises:
    _check(
        "a: 1\nb: 2\n",
        '{"a":1,"b":2}',
        "a: 1\nb: 2\n",
    )
    _check(
        "- 1\n- 2\n",
        "[1,2]",
        "- 1\n- 2\n",
    )
    _check(
        "a:\n  b:\n    c: d\n",
        '{"a":{"b":{"c":"d"}}}',
        "a:\n  b:\n    c: d\n",
    )
    _check(
        "a:\n- 1\n- 2\n",
        '{"a":[1,2]}',
        "a:\n- 1\n- 2\n",
    )
    _check(
        "a:\n  - 1\n  - 2\n",
        '{"a":[1,2]}',
        "a:\n- 1\n- 2\n",
    )
    _check(
        "- a: 1\n  b: 2\n- 3\n",
        '[{"a":1,"b":2},3]',
        "- a: 1\n  b: 2\n- 3\n",
    )
    _check(
        "- - 1\n  - 2\n- - 3\n",
        "[[1,2],[3]]",
        "- - 1\n  - 2\n- - 3\n",
    )
    _check(
        "outer:\n  inner:\n  - x: 1\n    y: 2\n  - z\n",
        '{"outer":{"inner":[{"x":1,"y":2},"z"]}}',
        "outer:\n  inner:\n  - x: 1\n    y: 2\n  - z\n",
    )


def test_matches_pyyaml_001() raises:
    _check(
        "a: 1\n\n\nb: 2\n",
        '{"a":1,"b":2}',
        "a: 1\nb: 2\n",
    )
    _check(
        "# lead\na: 1  # trail\n# tail\n",
        '{"a":1}',
        "a: 1\n",
    )
    _check(
        "empty:\nalso:\n",
        '{"empty":null,"also":null}',
        "also: null\nempty: null\n",
    )
    _check(
        "a: {}\nb: []\n",
        '{"a":{},"b":[]}',
        "a: {}\nb: []\n",
    )
    _check(
        "s: plain text\n",
        '{"s":"plain text"}',
        "s: plain text\n",
    )
    _check(
        "s: 'single'\ns2: 'it''s'\n",
        '{"s":"single","s2":"it\'s"}',
        "s: single\ns2: it's\n",
    )
    _check(
        's: "double"\ns2: "tab\\there"\ns3: "\\u00e9"\n',
        '{"s":"double","s2":"tab\\there","s3":"\\u00e9"}',
        's: double\ns2: "tab\\there"\ns3: "\\xE9"\n',
    )
    _check(
        "n: null\nn2: ~\nn3: Null\n",
        '{"n":null,"n2":null,"n3":null}',
        "n: null\nn2: null\nn3: null\n",
    )


def test_matches_pyyaml_002() raises:
    _check(
        "b: true\nb2: False\nb3: yes\nb4: OFF\n",
        '{"b":true,"b2":false,"b3":true,"b4":false}',
        "b: true\nb2: false\nb3: true\nb4: false\n",
    )
    _check(
        "i: 0\ni2: -5\ni3: 0o17\ni4: 017\ni5: 0x1f\ni6: 0b11\ni7: 1_000\n",
        '{"i":0,"i2":-5,"i3":"0o17","i4":15,"i5":31,"i6":3,"i7":1000}',
        "i: 0\ni2: -5\ni3: 0o17\ni4: 15\ni5: 31\ni6: 3\ni7: 1000\n",
    )
    _check(
        "not_num: 1e3\nnot_num2: 0o17\nnot_num3: 08\n",
        '{"not_num":"1e3","not_num2":"0o17","not_num3":"08"}',
        "not_num: 1e3\nnot_num2: 0o17\nnot_num3: 08\n",
    )
    _check(
        "long: this is a fairly long plain scalar that keeps going\n",
        '{"long":"this is a fairly long plain scalar that keeps going"}',
        "long: this is a fairly long plain scalar that keeps going\n",
    )
    _check(
        "folded: this spans\n  several lines\n  in one scalar\n",
        '{"folded":"this spans several lines in one scalar"}',
        "folded: this spans several lines in one scalar\n",
    )
    _check(
        "blank_fold: one\n\n  two\n",
        '{"blank_fold":"one\\ntwo"}',
        "blank_fold: 'one\n\n  two'\n",
    )
    _check(
        "lit: |\n  a\n  b\n",
        '{"lit":"a\\nb\\n"}',
        "lit: 'a\n\n  b\n\n  '\n",
    )
    _check(
        "lit_strip: |-\n  a\n",
        '{"lit_strip":"a"}',
        "lit_strip: a\n",
    )


def test_matches_pyyaml_003() raises:
    _check(
        "lit_keep: |+\n  a\n\n",
        '{"lit_keep":"a\\n\\n"}',
        "lit_keep: 'a\n\n\n  '\n",
    )
    _check(
        "fold: >\n  a\n  b\n",
        '{"fold":"a b\\n"}',
        "fold: 'a b\n\n  '\n",
    )
    _check(
        "fold_more: >\n  a\n   indented\n  b\n",
        '{"fold_more":"a\\n indented\\nb\\n"}',
        'fold_more: "a\\n indented\\nb\\n"\n',
    )
    _check(
        "lit_indent: |2\n   a\n",
        '{"lit_indent":" a\\n"}',
        "lit_indent: ' a\n\n  '\n",
    )
    _check(
        "empty_str: ''\n",
        '{"empty_str":""}',
        "empty_str: ''\n",
    )
    _check(
        "spaces: '  padded  '\n",
        '{"spaces":"  padded  "}',
        "spaces: '  padded  '\n",
    )
    _check(
        "a: [1, 2, 3]\n",
        '{"a":[1,2,3]}',
        "a:\n- 1\n- 2\n- 3\n",
    )
    _check(
        "a: {x: 1, y: 2}\n",
        '{"a":{"x":1,"y":2}}',
        "a:\n  x: 1\n  y: 2\n",
    )


def test_matches_pyyaml_004() raises:
    _check(
        "a: [{b: 1}, [2, 3]]\n",
        '{"a":[{"b":1},[2,3]]}',
        "a:\n- b: 1\n- - 2\n  - 3\n",
    )
    _check(
        "a: [\n  1,\n  2,\n]\n",
        '{"a":[1,2]}',
        "a:\n- 1\n- 2\n",
    )
    _check(
        "a: {x}\n",
        '{"a":{"x":null}}',
        "a:\n  x: null\n",
    )
    _check(
        "a: [a:b]\n",
        '{"a":["a:b"]}',
        "a:\n- a:b\n",
    )
    _check(
        "a: &x 1\nb: *x\n",
        '{"a":1,"b":1}',
        "a: 1\nb: 1\n",
    )
    _check(
        "a: &x [1, 2]\nb: *x\n",
        '{"a":[1,2],"b":[1,2]}',
        "a: &id001\n- 1\n- 2\nb: *id001\n",
    )
    _check(
        "base: &b {x: 1, y: 2}\nd:\n  <<: *b\n  y: 3\n",
        '{"base":{"x":1,"y":2},"d":{"x":1,"y":3}}',
        "base:\n  x: 1\n  y: 2\nd:\n  x: 1\n  y: 3\n",
    )
    _check(
        "base: &b {x: 1}\nb2: &c {y: 2}\nd:\n  <<: [*b, *c]\n  z: 3\n",
        '{"base":{"x":1},"b2":{"y":2},"d":{"y":2,"x":1,"z":3}}',
        "b2:\n  y: 2\nbase:\n  x: 1\nd:\n  x: 1\n  y: 2\n  z: 3\n",
    )


def test_matches_pyyaml_005() raises:
    _check(
        (
            'a: !!str 1\nb: !!int "2"\nc: !!float "3"\nd: !!bool "yes"\ne:'
            ' !!null ""\n'
        ),
        '{"a":"1","b":2,"c":3.0,"d":true,"e":null}',
        "a: '1'\nb: 2\nc: 3.0\nd: true\ne: null\n",
    )
    _check(
        "---\na: 1\n",
        '{"a":1}',
        "a: 1\n",
    )
    _check(
        "---\na: 1\n...\n",
        '{"a":1}',
        "a: 1\n",
    )
    _check(
        "'<<': 1\n",
        '{"<<":1}',
        "'<<': 1\n",
    )
    _check(
        '"<<": 1\n',
        '{"<<":1}',
        "'<<': 1\n",
    )
    _check(
        "{'<<': 1}\n",
        '{"<<":1}',
        "'<<': 1\n",
    )
    _check(
        "a: 1:59\nb: 1:30\nc: 1:0\nd: 1:00\ne: 12:34:56\nf: 1_0:30\n",
        '{"a":119,"b":90,"c":60,"d":60,"e":45296,"f":630}',
        "a: 119\nb: 90\nc: 60\nd: 60\ne: 45296\nf: 630\n",
    )
    _check(
        "a: 1:60\nb: 1:99\nc: 1:005\nd: 0:30\ne: 01:30\n",
        '{"a":"1:60","b":"1:99","c":"1:005","d":"0:30","e":"01:30"}',
        "a: 1:60\nb: 1:99\nc: 1:005\nd: 0:30\ne: 01:30\n",
    )


def test_matches_pyyaml_006() raises:
    _check(
        "a: 1:30.5\nb: 0:30.5\nc: 1:2:3.5\nd: 1:60.5\n",
        '{"a":90.5,"b":30.5,"c":3723.5,"d":"1:60.5"}',
        "a: 90.5\nb: 30.5\nc: 3723.5\nd: 1:60.5\n",
    )
    _check(
        "'q key': 1\n",
        '{"q key":1}',
        "q key: 1\n",
    )
    _check(
        '"d key": 1\n',
        '{"d key":1}',
        "d key: 1\n",
    )
    _check(
        "a b c: 1\n",
        '{"a b c":1}',
        "a b c: 1\n",
    )
    _check(
        "{}\n",
        "{}",
        "{}\n",
    )
    _check(
        (
            "- - - -638\n    - 98.6738\n  - 21.946\n- x17:\n  - '123'\n- - {}\n"
            "  - null\n"
        ),
        '[[[-638,98.6738],21.946],{"x17":["123"]},[{},null]]',
        (
            "- - - -638\n    - 98.6738\n  - 21.946\n- x17:\n  - '123'\n- - {}\n"
            "  - null\n"
        ),
    )
    _check(
        "'1.5'\n",
        '"1.5"',
        "'1.5'\n",
    )
    _check(
        "- []\n- -2.371\n- ''\n",
        '[[],-2.371,""]',
        "- []\n- -2.371\n- ''\n",
    )


def test_matches_pyyaml_007() raises:
    _check(
        "[]\n",
        "[]",
        "[]\n",
    )
    _check(
        "'line\n\n  break'\n",
        '"line\\nbreak"',
        "'line\n\n  break'\n",
    )
    _check(
        "'*star'\n",
        '"*star"',
        "'*star'\n",
    )
    _check(
        "- {}\n- -78\n- key18:\n  - '  padded '\n  - -35.2404\n",
        '[{},-78,{"key18":["  padded ",-35.2404]}]',
        "- {}\n- -78\n- key18:\n  - '  padded '\n  - -35.2404\n",
    )
    _check(
        "true\n...\n",
        "true",
        "true\n...\n",
    )
    _check(
        "'  padded '\n",
        '"  padded "',
        "'  padded '\n",
    )
    _check(
        "日本語\n...\n",
        '"\\u65e5\\u672c\\u8a9e"',
        '"\\u65E5\\u672C\\u8A9E"\n',
    )
    _check(
        "'true'\n",
        '"true"',
        "'true'\n",
    )


def test_matches_pyyaml_008() raises:
    _check(
        "'*star'\n",
        '"*star"',
        "'*star'\n",
    )
    _check(
        "nested1:\n  nested14: 'a #b'\n",
        '{"nested1":{"nested14":"a #b"}}',
        "nested1:\n  nested14: 'a #b'\n",
    )
    _check(
        "a9:\n- true\n- null\nlong_key_name0: it's\nnested5: {}\n",
        '{"a9":[true,null],"long_key_name0":"it\'s","nested5":{}}',
        "a9:\n- true\n- null\nlong_key_name0: it's\nnested5: {}\n",
    )
    _check(
        "-x\n...\n",
        '"-x"',
        "-x\n...\n",
    )
    _check(
        "null\n...\n",
        "null",
        "null\n...\n",
    )
    _check(
        "null\n...\n",
        "null",
        "null\n...\n",
    )
    _check(
        "{}\n",
        "{}",
        "{}\n",
    )
    _check(
        '"\\u65E5\\u672C\\u8A9E"\n',
        '"\\u65e5\\u672c\\u8a9e"',
        '"\\u65E5\\u672C\\u8A9E"\n',
    )


def test_matches_pyyaml_009() raises:
    _check(
        "k215: ''\n",
        '{"k215":""}',
        "k215: ''\n",
    )
    _check(
        "null\n...\n",
        "null",
        "null\n...\n",
    )
    _check(
        "k17: '1.5'\nkey1:\n- {}\nlong_key_name1: -995\n",
        '{"k17":"1.5","key1":[{}],"long_key_name1":-995}',
        "k17: '1.5'\nkey1:\n- {}\nlong_key_name1: -995\n",
    )
    _check(
        "{}\n",
        "{}",
        "{}\n",
    )
    _check(
        "plain\n...\n",
        '"plain"',
        "plain\n...\n",
    )
    _check(
        "- []\n",
        "[[]]",
        "- []\n",
    )
    _check(
        (
            "- {}\n- nested7: null\n- - - 99.7713\n    - it's\n    - ''\n  -"
            " {}\n  - {}\n"
        ),
        '[{},{"nested7":null},[[99.7713,"it\'s",""],{},{}]]',
        (
            "- {}\n- nested7: null\n- - - 99.7713\n    - it's\n    - ''\n  -"
            " {}\n  - {}\n"
        ),
    )
    _check(
        "k112:\n  a5:\n    b7: 'yes'\n    key12: null\n",
        '{"k112":{"a5":{"b7":"yes","key12":null}}}',
        "k112:\n  a5:\n    b7: 'yes'\n    key12: null\n",
    )


def test_matches_pyyaml_010() raises:
    _check(
        "false\n...\n",
        "false",
        "false\n...\n",
    )
    _check(
        (
            "a6:\n- - -x\n  - -x\n- null\nk11:\n  a8: {}\n  b18: {}\n  k16:"
            " []\nkey15:\n- []\n"
        ),
        '{"a6":[["-x","-x"],null],"k11":{"a8":{},"b18":{},"k16":[]},"key15":[[]]}',
        (
            "a6:\n- - -x\n  - -x\n- null\nk11:\n  a8: {}\n  b18: {}\n  k16:"
            " []\nkey15:\n- []\n"
        ),
    )
    _check(
        "true\n...\n",
        "true",
        "true\n...\n",
    )
    _check(
        "- k116: {}\n  k117:\n  - 'null'\n  long_key_name13: false\n- []\n",
        '[{"k116":{},"k117":["null"],"long_key_name13":false},[]]',
        "- k116: {}\n  k117:\n  - 'null'\n  long_key_name13: false\n- []\n",
    )
    _check(
        "-603\n...\n",
        "-603",
        "-603\n...\n",
    )
    _check(
        "{}\n",
        "{}",
        "{}\n",
    )
    _check(
        "true\n...\n",
        "true",
        "true\n...\n",
    )
    _check(
        "b3: false\n",
        '{"b3":false}',
        "b3: false\n",
    )


def test_matches_pyyaml_011() raises:
    _check(
        "- - - 98.3481\n",
        "[[[98.3481]]]",
        "- - - 98.3481\n",
    )
    _check(
        "[]\n",
        "[]",
        "[]\n",
    )
    _check(
        "{}\n",
        "{}",
        "{}\n",
    )
    _check(
        "-22.7539\n...\n",
        "-22.7539",
        "-22.7539\n...\n",
    )
    _check(
        "- - - null\n    - -990\n  - null\n",
        "[[[null,-990],null]]",
        "- - - null\n    - -990\n  - null\n",
    )
    _check(
        "{}\n",
        "{}",
        "{}\n",
    )
    _check(
        "k111: {}\nk27:\n  k26:\n    x14: '1.5'\nx2: []\n",
        '{"k111":{},"k27":{"k26":{"x14":"1.5"}},"x2":[]}',
        "k111: {}\nk27:\n  k26:\n    x14: '1.5'\nx2: []\n",
    )
    _check(
        "null\n...\n",
        "null",
        "null\n...\n",
    )


def test_matches_pyyaml_012() raises:
    _check(
        '- {}\n- false\n- "\\u65E5\\u672C\\u8A9E"\n',
        '[{},false,"\\u65e5\\u672c\\u8a9e"]',
        '- {}\n- false\n- "\\u65E5\\u672C\\u8A9E"\n',
    )
    _check(
        "{}\n",
        "{}",
        "{}\n",
    )
    _check(
        "- 日本語\n- long_key_name1: -77.7858\n- -x\n",
        '["\\u65e5\\u672c\\u8a9e",{"long_key_name1":-77.7858},"-x"]',
        '- "\\u65E5\\u672C\\u8A9E"\n- long_key_name1: -77.7858\n- -x\n',
    )
    _check(
        "- - {}\n- {}\n- 'null'\n",
        '[[{}],{},"null"]',
        "- - {}\n- {}\n- 'null'\n",
    )
    _check(
        "a13: false\n",
        '{"a13":false}',
        "a13: false\n",
    )
    _check(
        "null\n...\n",
        "null",
        "null\n...\n",
    )
    _check(
        "4.5431\n...\n",
        "4.5431",
        "4.5431\n...\n",
    )
    _check(
        "- 'true'\n- []\n",
        '["true",[]]',
        "- 'true'\n- []\n",
    )


def test_matches_pyyaml_013() raises:
    _check(
        "- null\n- a6:\n  - -557\n  - null\n  b4:\n    nested6: ''\n- 254\n",
        '[null,{"a6":[-557,null],"b4":{"nested6":""}},254]',
        "- null\n- a6:\n  - -557\n  - null\n  b4:\n    nested6: ''\n- 254\n",
    )
    _check(
        "false\n...\n",
        "false",
        "false\n...\n",
    )
    _check(
        "'a #b'\n",
        '"a #b"',
        "'a #b'\n",
    )
    _check(
        "- false\n",
        "[false]",
        "- false\n",
    )
    _check(
        "- false\n",
        "[false]",
        "- false\n",
    )
    _check(
        '"tab\\there"\n',
        '"tab\\there"',
        '"tab\\there"\n',
    )
    _check(
        "- a16:\n    a18: true\n    k14: it's\n",
        '[{"a16":{"a18":true,"k14":"it\'s"}}]',
        "- a16:\n    a18: true\n    k14: it's\n",
    )
    _check(
        "k213:\n- 48.0836\n",
        '{"k213":[48.0836]}',
        "k213:\n- 48.0836\n",
    )


def test_rejects_like_pyyaml_000() raises:
    with assert_raises():
        _ = safe_load("a: 1\n b: 2\n")
    with assert_raises():
        _ = safe_load("\ta: 1\n")
    with assert_raises():
        _ = safe_load("a: [1, 2\n")
    with assert_raises():
        _ = safe_load("a: {x: 1\n")
    with assert_raises():
        _ = safe_load("a: 'unterminated\n")
    with assert_raises():
        _ = safe_load('a: "unterminated\n')
    with assert_raises():
        _ = safe_load("a: *missing\n")
    with assert_raises():
        _ = safe_load('a: "\\q"\n')


def test_rejects_like_pyyaml_001() raises:
    with assert_raises():
        _ = safe_load("a: b: c\n")
    with assert_raises():
        _ = safe_load("a: - b\n")
    with assert_raises():
        _ = safe_load("a: - b\n  - c\n")


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
