# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #
"""Render the files of a scaffold's subclass skeleton.

Each ``render_*`` function returns one generated file's text, and the
renderers that can hit something they can't trace also return warnings for
the user. :func:`render_skeleton` renders the whole set from a resolved
donor.
"""

from __future__ import annotations

import ast
import copy
import sys
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from pathlib import Path

try:
    from .donor import Donor, DonorKeyword
    from .max_arch_paths import ImportedName, ParsedModule, free_names
except ImportError:
    # Standalone invocation: `python /path/to/scaffold.py ...`
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from donor import Donor, DonorKeyword  # type: ignore[no-redef]
    from max_arch_paths import (  # type: ignore[no-redef]
        ImportedName,
        ParsedModule,
        free_names,
    )


_GENERATED_HEADER = (
    "# Generated by scaffold.py. Edit the TODOs as you discover deltas.\n"
)


def _import_sort_key(name: str) -> tuple[int, str]:
    """isort's ``order-by-type``: CONSTANTS, then Classes, then functions."""
    bare = name.split(" as ")[0]
    if bare.isupper() and len(bare) > 1:
        return 0, bare
    if bare[:1].isupper():
        return 1, bare
    return 2, bare


def _render_section(
    plain: Iterable[str] = (), pairs: Iterable[tuple[str, str]] = ()
) -> str:
    """Render one isort section of imports, the way ruff's I001 orders it.

    ``plain`` holds whole ``import x`` lines and ``pairs`` holds
    ``(module, name)`` for ``from module import name``. Plain imports come
    first, then the ``from`` imports, each sorted by module. Names from the
    same module merge into one statement. Sorting the whole section matters
    because donor names can live anywhere (for example
    ``max.pipelines.architectures.deepseekV3.memory_planner``), and splicing
    one at a fixed position fails I001.
    """
    lines = sorted(set(plain), key=lambda line: line.split()[1].lower())
    by_module: dict[str, set[str]] = {}
    for module, name in pairs:
        by_module.setdefault(module, set()).add(name)
    for module in sorted(by_module, key=str.lower):
        names = sorted(by_module[module], key=_import_sort_key)
        line = f"from {module} import {', '.join(names)}"
        if len(line) > 80:
            body = "".join(f"    {name},\n" for name in names)
            line = f"from {module} import (\n{body})"
        lines.append(line)
    return "\n".join(lines)


def _render_relative_imports(pairs: Iterable[tuple[str, str]]) -> str:
    """Render ``from .module import name`` lines for the port's own files."""
    return "\n".join(
        f"from .{module} import {name}"
        for module, name in sorted(pairs, key=lambda p: p[0].lower())
    )


def _donor_alias(donor_name: str, port_name: str) -> str:
    """Import alias for a donor class whose name the port class reuses.

    Scaffolding ``Olmo3ForCausalLM`` from ``olmo3`` would otherwise define
    ``class Olmo3Model(Olmo3Model)``.
    """
    return f"Donor{donor_name}" if donor_name == port_name else donor_name


def _import_name(donor_name: str, alias: str) -> str:
    return donor_name if alias == donor_name else f"{donor_name} as {alias}"


def render_init(slug: str) -> str:
    return f'''{_GENERATED_HEADER}"""Custom-arch entry point. ``max serve --custom-architectures <path>`` reads
``ARCHITECTURES`` from this module.
"""

from .arch import {slug}_arch

ARCHITECTURES = [{slug}_arch]
'''


def _render_imports(extras: Iterable[tuple[str, str]] = ()) -> str:
    """Render arch.py's ``max`` import block with donor ``extras`` merged."""
    modules = [
        ("max.graph.weights", "WeightsFormat"),
        ("max.pipelines.lib", "SupportedArchitecture"),
        *extras,
    ]
    return _render_section(pairs=modules)


# ``SupportedArchitecture`` keywords the generated arch.py writes itself.
# Most name the port's own repo and classes. The port's weight adapter reads
# safetensors only, and the port registers bfloat16 until its author
# confirms the checkpoint dtype. Every other keyword the donor sets carries
# over verbatim.
#
# A carried keyword brings the imports its value reads and nothing else.
# Side-effect imports in the donor's arch.py stay behind: nemotron_h_modulev3
# imports the qwen3_5 parser modules so that ``reasoning_parser="qwen3_5"``
# names a registered parser. The port still registers them, because its
# model.py imports from the donor package, whose ``__init__`` imports the
# donor's arch.py.
PORT_KEYWORDS = frozenset(
    {
        "name",
        "example_repo_ids",
        "pipeline_model",
        "config",
        "weight_adapters",
        "default_weights_format",
        "default_encoding",
        "supported_encodings",
    }
)

_CARRIED_HEADER = (
    "    # Carried verbatim from the donor's arch.py. The port inherits the\n"
    "    # donor's ModuleV3 pipeline model, so its serving settings apply.\n"
)
_PLANNER_NOTE = (
    "    # KV-cache models need a planner. Without one, MAX budgets no"
    " activation\n"
    "    # memory. Inherited from the donor. Override it if the port"
    " diverges.\n"
)
_PLANNER_ABSENT = (
    "    # TODO(port): the donor sets no memory_planner, which is\n"
    "    # correct only for architectures that do their own memory\n"
    "    # estimation (diffusion, embedding). If this port uses a\n"
    "    # KV cache, add memory_planner=PagedMemoryPlanner.\n"
)


def _port_bindings(slug: str, short: str) -> dict[str, ImportedName | None]:
    """Module-scope names the generated arch.py binds itself.

    Imported names map to their import. The port's own modules, classes
    and registration map to ``None``.
    """
    return {
        "WeightsFormat": ImportedName("max.graph.weights", "WeightsFormat"),
        "SupportedArchitecture": ImportedName(
            "max.pipelines.lib", "SupportedArchitecture"
        ),
        "weight_adapters": None,
        f"{short}Model": None,
        f"{short}Config": None,
        f"{slug}_arch": None,
    }


def _carried_alias(name: str) -> str:
    """Name for a carried import that would shadow one of the port's names."""
    return f"donor_{name}" if name[:1].islower() else f"Donor{name}"


def _carry(
    value: DonorKeyword, *, slug: str, short: str
) -> tuple[str, list[tuple[str, str]]]:
    """Rewrite one resolved keyword value for the port's arch.py.

    The donor's ``pipeline_model=`` and ``config=`` classes become the
    port's ``{short}Model`` and ``{short}Config``, which subclass them: a
    donor's ``batching=NemotronHModel.batch_processor_cls`` reads the
    port's attribute, so an override in the port takes effect. Any other
    name that the port's arch.py binds to something else is imported under
    an alias. Returns the value text and the ``(module, name)`` imports it
    needs.
    """
    assert value.expr is not None
    bindings = _port_bindings(slug, short)
    imports: list[tuple[str, str]] = []
    edits: list[tuple[int, int, str]] = []
    for carried in value.names:
        if carried.role == "model":
            target = f"{short}Model"
        elif carried.role == "config":
            target = f"{short}Config"
        else:
            target = carried.name
            if (
                carried.name in bindings
                and bindings[carried.name] != carried.source
            ):
                target = _carried_alias(carried.name)
            imports.append(
                (
                    carried.source.module,
                    _import_name(carried.source.name, target),
                )
            )
        if target != carried.name:
            edits.extend((start, end, target) for start, end in carried.spans)
    expr = value.expr
    for start, end, target in sorted(edits, reverse=True):
        expr = expr[:start] + target + expr[end:]
    return expr, imports


@dataclass
class _Keywords:
    """The carried keywords' lines, and what rendering them needs."""

    text: str
    imports: list[tuple[str, str]]
    warnings: list[str]


def _render_keywords(
    donor_keywords: Mapping[str, DonorKeyword], *, slug: str, short: str
) -> _Keywords:
    """Render every donor keyword outside ``PORT_KEYWORDS``, in donor order.

    A donor without ``memory_planner`` gets a TODO in its place, and so does
    a keyword whose value can't be traced, with a warning.
    """
    lines = []
    imports: list[tuple[str, str]] = []
    warnings = []
    for keyword, value in donor_keywords.items():
        if keyword in PORT_KEYWORDS:
            continue
        if value.expr is None:
            warnings.append(
                f"the donor's arch.py sets {keyword}, but scaffold.py could "
                f"not follow the import that defines it. Copy the donor's "
                f"{keyword}= line into arch.py by hand."
            )
            lines.append(
                f"    # TODO(port): copy the donor's {keyword}= line here.\n"
            )
            continue
        expr, needed = _carry(value, slug=slug, short=short)
        imports.extend(needed)
        note = _PLANNER_NOTE if keyword == "memory_planner" else ""
        lines.append(f"{note}    {keyword}={expr},\n")
    if "memory_planner" not in donor_keywords:
        lines.append(_PLANNER_ABSENT)
    return _Keywords(_CARRIED_HEADER + "".join(lines), imports, warnings)


def render_arch(
    *,
    slug: str,
    arch_name: str,
    short: str,
    hf_id: str,
    donor_keywords: Mapping[str, DonorKeyword],
) -> tuple[str, list[str]]:
    """Render arch.py from every keyword the donor's arch.py sets.

    ``donor_keywords`` is :attr:`Donor.keywords`. Keywords in
    ``PORT_KEYWORDS`` are skipped. Returns the file and its warnings.
    """
    keywords = _render_keywords(donor_keywords, slug=slug, short=short)
    return (
        f'''{_GENERATED_HEADER}"""Registers ``{arch_name}`` with {short}Model and {short}Config."""

{_render_imports(keywords.imports)}

from . import weight_adapters
from .model import {short}Model
from .model_config import {short}Config

{slug}_arch = SupportedArchitecture(
    name="{arch_name}",
    example_repo_ids=["{hf_id}"],
    default_encoding="bfloat16",
    supported_encodings={{"bfloat16"}},
    pipeline_model={short}Model,
    default_weights_format=WeightsFormat.safetensors,
    weight_adapters={{
        WeightsFormat.safetensors: weight_adapters.convert_safetensor_state_dict,
    }},
    config={short}Config,
{keywords.text})
''',
        keywords.warnings,
    )


def render_config(*, donor: Donor, short: str) -> str:
    config = donor.config.name
    alias = _donor_alias(config, f"{short}Config")
    if donor.builds_config:
        caller = (
            f"{short}Model._create_model_config calls this with the {config}\n"
            f"        the donor pipeline model built and finalized."
        )
    else:
        caller = (
            f"The donor's _create_model_config returns no config, so nothing\n"
            f"        calls this yet. Override {short}Model._create_model_config"
            f"\n        to build a {config} and pass it here."
        )
    imports = _render_section(
        pairs=[
            (donor.config.module, _import_name(config, alias)),
            ("transformers", "AutoConfig"),
        ]
    )
    return f'''{_GENERATED_HEADER}"""Config for the {short} port.

Subclasses {config} from the {donor.slug} donor. Add a field for each
config.json key the donor doesn't read (MuP scalars, custom RoPE fields,
novel attention params, …) and set it in ``from_donor``.
"""

from __future__ import annotations

from dataclasses import dataclass, fields

{imports}


@dataclass(kw_only=True)
class {short}Config({alias}):
    # TODO(port): declare novel fields with defaults. Examples:
    #   embedding_multiplier: float = 1.0
    #   residual_multiplier: float = 1.0

    @classmethod
    def from_donor(
        cls, donor_config: {alias}, huggingface_config: AutoConfig
    ) -> {short}Config:
        """Re-types the donor's finished config and reads novel HF fields.

        {caller}
        """
        # Every donor field carries over, including the ones the donor set
        # after construction (mesh, quant_config, return_logits, ...). The
        # port's own fields start at their defaults.
        donor_fields = {{f.name for f in fields(donor_config)}}
        cfg = cls(
            **{{
                f.name: getattr(donor_config, f.name)
                for f in fields(cls)
                if f.init and f.name in donor_fields
            }}
        )
        # TODO(port): read novel HF config fields and set them on `cfg`. Examples:
        #   cfg.embedding_multiplier = huggingface_config.scale_emb       # MuP
        #   cfg.residual_multiplier = (
        #       huggingface_config.scale_depth / huggingface_config.num_hidden_layers ** 0.5
        #   )
        return cfg
'''


class _RenameName(ast.NodeTransformer):
    def __init__(self, old: str, new: str) -> None:
        self.old = old
        self.new = new

    def visit_Name(self, node: ast.Name) -> ast.Name:
        if node.id == self.old:
            node.id = self.new
        return node


@dataclass
class _BodyImports:
    """Imports a copied method body needs, split the way isort groups them."""

    stdlib: list[str]
    """``import x`` lines from the standard library."""
    third_party: list[str]
    """``import x`` lines from anywhere else."""
    names: list[tuple[str, str]]
    """``(module, name)`` pairs for ``from module import name``."""
    warnings: list[str] = field(default_factory=list)
    """Names the body reads that no import or definition provides."""


def _plain_import(parsed: ParsedModule, name: str) -> str | None:
    """The ``import x`` / ``import x as y`` line that binds ``name``."""
    for node in parsed.tree.body:
        if not isinstance(node, ast.Import):
            continue
        for alias in node.names:
            bound = alias.asname or alias.name.split(".")[0]
            if bound != name:
                continue
            if alias.asname:
                return f"import {alias.name} as {alias.asname}"
            return f"import {alias.name}"
    return None


def _render_instantiate(donor: Donor, short: str) -> tuple[str, _BodyImports]:
    """Render the donor's ``_instantiate_module`` building ``short``.

    Returns the method source and the imports its body needs from outside
    the port package.
    """
    parsed, donor_fn = donor.instantiate
    fn = copy.deepcopy(donor_fn)
    fn = _RenameName(donor.module.name, short).visit(fn)
    ast.fix_missing_locations(fn)
    body = [
        stmt
        for stmt in fn.body
        if not (
            isinstance(stmt, ast.Expr)
            and isinstance(stmt.value, ast.Constant)
            and isinstance(stmt.value.value, str)
        )
    ]
    fn.body = body

    imports = _BodyImports(stdlib=[], third_party=[], names=[])
    args = fn.args
    params = {
        a.arg for a in (*args.posonlyargs, *args.args, *args.kwonlyargs)
    } | {a.arg for a in (args.vararg, args.kwarg) if a is not None}
    reads = dict.fromkeys(node.id for node in free_names(fn.body, params))
    for name in reads:
        if name == short:
            continue
        plain = _plain_import(parsed, name)
        if plain is not None:
            top = plain.split()[1].split(".")[0]
            if top in sys.stdlib_module_names:
                imports.stdlib.append(plain)
            else:
                imports.third_party.append(plain)
            continue
        imported = parsed.imports.get(name)
        if imported is None and parsed.defines(name):
            imported = ImportedName(parsed.module, name)
        if imported is None:
            imports.warnings.append(
                f"{donor.model.name}._instantiate_module uses {name!r}, "
                f"which scaffold.py could not trace to an import. Add the "
                f"import to model.py by hand."
            )
            continue
        imports.names.append(
            (imported.module, _import_name(imported.name, name))
        )

    param = fn.args.args[1].arg if len(fn.args.args) > 1 else "model_config"
    lines = []
    for stmt in body:
        lines.extend(ast.unparse(stmt).splitlines())
    rendered = "\n".join(f"        {line}" for line in lines)
    source = (
        f"    def _instantiate_module(self, {param}: Any) -> Any:\n"
        f"        # Same arguments and placement as "
        f"{donor.model.name}._instantiate_module.\n"
        f"{rendered}\n"
    )
    return source, imports


def render_model(
    *, slug: str, donor: Donor, short: str
) -> tuple[str, list[str]]:
    """Render model.py. Returns the file and its warnings."""
    model = donor.model.name
    alias = _donor_alias(model, f"{short}Model")
    instantiate, body_imports = _render_instantiate(donor, short)
    stdlib = _render_section(
        plain=body_imports.stdlib,
        pairs=[("typing", "Any"), ("typing", "ClassVar")],
    )
    imports = _render_section(
        plain=body_imports.third_party,
        pairs=[
            (donor.model.module, _import_name(model, alias)),
            *body_imports.names,
        ],
    )
    local = _render_relative_imports(
        [("model_config", f"{short}Config"), (slug, short)]
    )
    if donor.builds_config:
        config_doc = (
            f"``_create_model_config`` re-types\n"
            f"the donor's config as ``{short}Config`` and "
        )
        create = (
            f"    def _create_model_config(self, state_dict: dict[str, Any]) "
            f"-> Any:\n"
            f"        donor_config = super()._create_model_config(state_dict)\n"
            f"        return {short}Config.from_donor(donor_config, "
            f"self.huggingface_config)\n\n"
        )
    else:
        # The donor returns no config, so there is nothing to re-type.
        config_doc = "The donor builds no\nconfig object, and "
        create = ""
    return (
        f'''{_GENERATED_HEADER}"""Pipeline model for the {short} port.

Subclasses {model} from the {donor.slug} donor, a ModuleV3 pipeline model:
the base ``load_model`` builds the root module under ``F.lazy()`` and
compiles it with the checkpoint weights. {config_doc}``_instantiate_module`` builds
the port's root module ``{short}``.
"""

from __future__ import annotations

{stdlib}

{imports}

{local}


class {short}Model({alias}):
    model_config_cls: ClassVar[type[Any]] = {short}Config

{create}{instantiate}''',
        body_imports.warnings,
    )


def render_module(*, donor: Donor, short: str) -> str:
    root = donor.module.name
    alias = _donor_alias(root, short)
    imports = _render_section(
        pairs=[(donor.module.module, _import_name(root, alias))]
    )
    return f'''{_GENERATED_HEADER}"""Root module for the {short} port.

Subclasses {root} from the {donor.slug} donor, a ``max.experimental.nn.Module``.
Override ``__init__`` for structural deltas (norm variants, RoPE tweaks, MuP
scalars read from ``{short}Config``) and ``forward()`` for dataflow deltas.
Debug a layer by adding ``F.print(tensor, "name")`` taps in ``forward()``.
For a 1:1 port, no overrides are needed.
"""

from __future__ import annotations

from typing import Any

{imports}


class {short}({alias}):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        # {short}Model._instantiate_module passes the donor's constructor
        # arguments, config first. See model.py.
        super().__init__(*args, **kwargs)
        # TODO(port): apply structural deltas not covered by config fields.
'''


def render_weight_adapter(
    *, donor_slug: str, donor_adapter: ImportedName | None
) -> tuple[str, list[str]]:
    """Render weight_adapters.py. Returns the file and its warnings."""
    if donor_adapter is None:
        warning = (
            f"could not find a safetensors adapter in the {donor_slug} "
            f"donor's arch.py. Generating a pass-through. HF keys that don't "
            f"match the module's parameter names make compile() raise "
            f"KeyError. Check the donor's weight_adapters and wire it in "
            f"manually."
        )
        return (
            f'''{_GENERATED_HEADER}"""Weight adapter. Default is a pass-through.

WARNING: no donor adapter was found at scaffold time. A pass-through keeps
HF-prefixed keys (``model.…``) that match no parameter, so ``compile()``
raises ``KeyError`` for the parameters they should feed.
Find the donor's adapter and delegate to it (or copy its mapping here).
"""

from __future__ import annotations

from typing import Any

from max.graph.weights import WeightData, Weights


def convert_safetensor_state_dict(
    state_dict: dict[str, Weights], **unused_kwargs: Any
) -> dict[str, WeightData]:
    """Pass-through. Edit if HF keys don't match the donor's parameter names."""
    # TODO: strip a common prefix or remap fused/unfused QKV here if needed.
    return {{k: v.data() for k, v in state_dict.items()}}
''',
            [warning],
        )

    module, fn = donor_adapter
    import_line = f"from {module} import {fn} as _donor_convert"
    if len(import_line) > 80:
        import_line = f"from {module} import (\n    {fn} as _donor_convert,\n)"
    return (
        f'''{_GENERATED_HEADER}"""Weight adapter. Delegates to the {donor_slug} donor's adapter.

The donor adapter maps HF keys onto the donor module's parameter names. A
pass-through would leave those parameters without a matching key, and
``compile()`` would raise ``KeyError``. When your checkpoint's keys diverge
from the donor's, copy the donor's mapping into this file and edit it (see
references/rename-weights.md). ``compile()`` also rejects a tensor whose dtype
differs from its parameter's, such as a float32 checkpoint for a bfloat16
port: cast those tensors here (see references/pitfalls-weights.md).
"""

from __future__ import annotations

from typing import Any

from max.graph.weights import WeightData, Weights
{import_line}


def convert_safetensor_state_dict(
    state_dict: dict[str, Weights], **kwargs: Any
) -> dict[str, WeightData]:
    # The pipeline passes huggingface_config and pipeline_config as keywords
    # (encoder pipelines pass none). Forward them as received, because donor
    # adapters take different signatures.
    # TODO: if HF keys diverge from the donor's, copy the donor's mapping
    # here and rewrite the keys in this function.
    return _donor_convert(state_dict, **kwargs)
''',
        [],
    )


@dataclass
class Skeleton:
    """The rendered subclass skeleton."""

    files: dict[str, str]
    """Each generated file's text, keyed by file name."""
    warnings: list[str]
    """What the renderers couldn't trace. Show these to the user."""


def render_skeleton(
    *, slug: str, short: str, arch_name: str, hf_id: str, donor: Donor
) -> Skeleton:
    """Render every file of the subclass skeleton.

    Raises:
        DonorError: The donor has no single root module or config class
            to subclass.
    """
    arch, arch_warnings = render_arch(
        slug=slug,
        arch_name=arch_name,
        short=short,
        hf_id=hf_id,
        donor_keywords=donor.keywords,
    )
    model, model_warnings = render_model(slug=slug, donor=donor, short=short)
    adapter, adapter_warnings = render_weight_adapter(
        donor_slug=donor.slug, donor_adapter=donor.safetensors_adapter
    )
    files = {
        "__init__.py": render_init(slug),
        "arch.py": arch,
        "model_config.py": render_config(donor=donor, short=short),
        "model.py": model,
        f"{slug}.py": render_module(donor=donor, short=short),
        "weight_adapters.py": adapter,
    }
    return Skeleton(files, [*arch_warnings, *model_warnings, *adapter_warnings])
