"""Differential tests against `tomllib` and `tomli_w`.

Generated by `scripts/gen_toml_compat_cases.py`, which runs every case
through the reference implementations and records what they produced.
Do not edit by hand; add cases to the generator and re-run it.
"""

from std.testing import TestSuite, assert_equal, assert_raises

from json import dumps as json_dumps
from toml import dumps, loads


def _check(
    text: StringSlice,
    loaded: StringSlice,
    dumped: StringSlice,
    multiline: StringSlice,
) raises:
    """Checks one document against the reference implementations.

    Args:
        text: The document to load.
        loaded: What `tomllib.loads` produced, as compact JSON.
        dumped: What `tomli_w.dumps` produced for that value.
        multiline: What `tomli_w.dumps` produced with
            `multiline_strings=True`.

    Raises:
        If loading or writing differs from the reference.
    """
    var doc = loads(text)
    assert_equal(json_dumps(doc, separators=(",", ":")), loaded, String(text))
    assert_equal(dumps(doc), dumped, String(text))
    assert_equal(dumps(doc, multiline_strings=True), multiline, String(text))


def test_matches_tomllib_000() raises:
    _check(
        'key = "value"\n',
        '{"key":"value"}',
        'key = "value"\n',
        'key = "value"\n',
    )
    _check(
        "bare_key = 1\nbare-key = 2\n1234 = 3\n",
        '{"bare_key":1,"bare-key":2,"1234":3}',
        "bare_key = 1\nbare-key = 2\n1234 = 3\n",
        "bare_key = 1\nbare-key = 2\n1234 = 3\n",
    )
    _check(
        '"quoted key" = 1\n\'literal key\' = 2\n"" = 3\n',
        '{"quoted key":1,"literal key":2,"":3}',
        '"quoted key" = 1\n"literal key" = 2\n"" = 3\n',
        '"quoted key" = 1\n"literal key" = 2\n"" = 3\n',
    )
    _check(
        '"\\u00e9" = 1\n"\\U0001F600" = 2\n',
        '{"\\u00e9":1,"\\ud83d\\ude00":2}',
        '"é" = 1\n"😀" = 2\n',
        '"é" = 1\n"😀" = 2\n',
    )
    _check(
        "a.b.c = 1\na.b.d = 2\n",
        '{"a":{"b":{"c":1,"d":2}}}',
        "[a.b]\nc = 1\nd = 2\n",
        "[a.b]\nc = 1\nd = 2\n",
    )
    _check(
        'physical.color = "orange"\nphysical.shape = "round"\n',
        '{"physical":{"color":"orange","shape":"round"}}',
        '[physical]\ncolor = "orange"\nshape = "round"\n',
        '[physical]\ncolor = "orange"\nshape = "round"\n',
    )
    _check(
        "x = 1 # trailing comment\n# whole line\n",
        '{"x":1}',
        "x = 1\n",
        "x = 1\n",
    )
    _check(
        "\n\n\na = 1\n\n\n",
        '{"a":1}',
        "a = 1\n",
        "a = 1\n",
    )


def test_matches_tomllib_001() raises:
    _check(
        "a = 1\r\nb = 2\r\n",
        '{"a":1,"b":2}',
        "a = 1\nb = 2\n",
        "a = 1\nb = 2\n",
    )
    _check(
        (
            'basic = "I\'m a string. \\"You can quote me\\".'
            ' Name\\tJos\\u00E9\\nLocation\\tSF."\n'
        ),
        (
            '{"basic":"I\'m a string. \\"You can quote me\\".'
            ' Name\\tJos\\u00e9\\nLocation\\tSF."}'
        ),
        (
            'basic = "I\'m a string. \\"You can quote me\\".'
            ' Name\tJosé\\nLocation\tSF."\n'
        ),
        (
            'basic = """\nI\'m a string. \\"You can quote me\\".'
            ' Name\tJosé\nLocation\tSF."""\n'
        ),
    )
    _check(
        'esc = "\\b\\t\\n\\f\\r\\"\\\\"\n',
        '{"esc":"\\b\\t\\n\\f\\r\\"\\\\"}',
        'esc = "\\b\t\\n\\f\\r\\"\\\\"\n',
        'esc = """\n\\b\t\n\\f\\r\\"\\\\"""\n',
    )
    _check(
        'ml = """\nRoses are red\nViolets are blue"""\n',
        '{"ml":"Roses are red\\nViolets are blue"}',
        'ml = "Roses are red\\nViolets are blue"\n',
        'ml = """\nRoses are red\nViolets are blue"""\n',
    )
    _check(
        (
            'ml_join = """\\\n  The quick brown \\\n  fox jumps over \\\n  the'
            ' lazy dog.\\\n  """\n'
        ),
        '{"ml_join":"The quick brown fox jumps over the lazy dog."}',
        'ml_join = "The quick brown fox jumps over the lazy dog."\n',
        'ml_join = "The quick brown fox jumps over the lazy dog."\n',
    )
    _check(
        'ml_quotes = """Here are two quotation marks: "". Simple enough."""\n',
        '{"ml_quotes":"Here are two quotation marks: \\"\\". Simple enough."}',
        'ml_quotes = "Here are two quotation marks: \\"\\". Simple enough."\n',
        'ml_quotes = "Here are two quotation marks: \\"\\". Simple enough."\n',
    )
    _check(
        "lit = 'C:\\\\Users\\\\nodejs\\\\templates'\n",
        '{"lit":"C:\\\\\\\\Users\\\\\\\\nodejs\\\\\\\\templates"}',
        'lit = "C:\\\\\\\\Users\\\\\\\\nodejs\\\\\\\\templates"\n',
        'lit = "C:\\\\\\\\Users\\\\\\\\nodejs\\\\\\\\templates"\n',
    )
    _check(
        "lit_quote = 'Tom \"Dubs\" Preston-Werner'\n",
        '{"lit_quote":"Tom \\"Dubs\\" Preston-Werner"}',
        'lit_quote = "Tom \\"Dubs\\" Preston-Werner"\n',
        'lit_quote = "Tom \\"Dubs\\" Preston-Werner"\n',
    )


def test_matches_tomllib_002() raises:
    _check(
        (
            "ml_lit = '''\nThe first newline is trimmed.\n   All other"
            " whitespace is preserved.\n'''\n"
        ),
        (
            '{"ml_lit":"The first newline is trimmed.\\n   All other whitespace'
            ' is preserved.\\n"}'
        ),
        (
            'ml_lit = "The first newline is trimmed.\\n   All other whitespace'
            ' is preserved.\\n"\n'
        ),
        (
            'ml_lit = """\nThe first newline is trimmed.\n   All other'
            ' whitespace is preserved.\n"""\n'
        ),
    )
    _check(
        "empty1 = \"\"\nempty2 = ''\nempty3 = \"\"\"\"\"\"\nempty4 = ''''''\n",
        '{"empty1":"","empty2":"","empty3":"","empty4":""}',
        'empty1 = ""\nempty2 = ""\nempty3 = ""\nempty4 = ""\n',
        'empty1 = ""\nempty2 = ""\nempty3 = ""\nempty4 = ""\n',
    )
    _check(
        'unicode = "\\u00e9\\u4e2d\\U0001F600"\n',
        '{"unicode":"\\u00e9\\u4e2d\\ud83d\\ude00"}',
        'unicode = "é中😀"\n',
        'unicode = "é中😀"\n',
    )
    _check(
        "a = 0\nb = +99\nc = -17\nd = 1_000\ne = 5_349_221\n",
        '{"a":0,"b":99,"c":-17,"d":1000,"e":5349221}',
        "a = 0\nb = 99\nc = -17\nd = 1000\ne = 5349221\n",
        "a = 0\nb = 99\nc = -17\nd = 1000\ne = 5349221\n",
    )
    _check(
        (
            "hex1 = 0xDEADBEEF\nhex2 = 0xdead_beef\noct = 0o755\nbin ="
            " 0b1101_0110\n"
        ),
        '{"hex1":3735928559,"hex2":3735928559,"oct":493,"bin":214}',
        "hex1 = 3735928559\nhex2 = 3735928559\noct = 493\nbin = 214\n",
        "hex1 = 3735928559\nhex2 = 3735928559\noct = 493\nbin = 214\n",
    )
    _check(
        "big = 9223372036854775807\nsmall = -9223372036854775808\n",
        '{"big":9223372036854775807,"small":-9223372036854775808}',
        "big = 9223372036854775807\nsmall = -9223372036854775808\n",
        "big = 9223372036854775807\nsmall = -9223372036854775808\n",
    )
    _check(
        (
            "f1 = 1.0\nf2 = 3.1415\nf3 = -0.01\nf4 = 5e+22\nf5 = 1e06\nf6 ="
            " -2E-2\n"
        ),
        '{"f1":1.0,"f2":3.1415,"f3":-0.01,"f4":5e+22,"f5":1000000.0,"f6":-0.02}',
        (
            "f1 = 1.0\nf2 = 3.1415\nf3 = -0.01\nf4 = 5e+22\nf5 = 1000000.0\nf6"
            " = -0.02\n"
        ),
        (
            "f1 = 1.0\nf2 = 3.1415\nf3 = -0.01\nf4 = 5e+22\nf5 = 1000000.0\nf6"
            " = -0.02\n"
        ),
    )
    _check(
        "f7 = 6.626e-34\nf8 = 224_617.445_991_228\n",
        '{"f7":6.626e-34,"f8":224617.445991228}',
        "f7 = 6.626e-34\nf8 = 224617.445991228\n",
        "f7 = 6.626e-34\nf8 = 224617.445991228\n",
    )


def test_matches_tomllib_003() raises:
    _check(
        "z1 = 0.0\nz2 = +0.0\nz3 = -0.0\n",
        '{"z1":0.0,"z2":0.0,"z3":-0.0}',
        "z1 = 0.0\nz2 = 0.0\nz3 = -0.0\n",
        "z1 = 0.0\nz2 = 0.0\nz3 = -0.0\n",
    )
    _check(
        "t = true\nf = false\n",
        '{"t":true,"f":false}',
        "t = true\nf = false\n",
        "t = true\nf = false\n",
    )
    _check(
        "a = [1, 2, 3]\n",
        '{"a":[1,2,3]}',
        "a = [\n    1,\n    2,\n    3,\n]\n",
        "a = [\n    1,\n    2,\n    3,\n]\n",
    )
    _check(
        'b = ["red", "yellow", "green"]\n',
        '{"b":["red","yellow","green"]}',
        'b = [\n    "red",\n    "yellow",\n    "green",\n]\n',
        'b = [\n    "red",\n    "yellow",\n    "green",\n]\n',
    )
    _check(
        "c = [[1, 2], [3, 4, 5]]\n",
        '{"c":[[1,2],[3,4,5]]}',
        (
            "c = [\n    [\n        1,\n        2,\n    ],\n    [\n        3,\n "
            "       4,\n        5,\n    ],\n]\n"
        ),
        (
            "c = [\n    [\n        1,\n        2,\n    ],\n    [\n        3,\n "
            "       4,\n        5,\n    ],\n]\n"
        ),
    )
    _check(
        "d = [ \"all\", 'strings', \"\"\"are the same\"\"\", '''type''' ]\n",
        '{"d":["all","strings","are the same","type"]}',
        (
            'd = [\n    "all",\n    "strings",\n    "are the same",\n   '
            ' "type",\n]\n'
        ),
        (
            'd = [\n    "all",\n    "strings",\n    "are the same",\n   '
            ' "type",\n]\n'
        ),
    )
    _check(
        "e = [ 0.1, 0.2, 0.5, 1, 2, 5 ]\n",
        '{"e":[0.1,0.2,0.5,1,2,5]}',
        "e = [\n    0.1,\n    0.2,\n    0.5,\n    1,\n    2,\n    5,\n]\n",
        "e = [\n    0.1,\n    0.2,\n    0.5,\n    1,\n    2,\n    5,\n]\n",
    )
    _check(
        'f = [ "Comma", "Trailing", ]\n',
        '{"f":["Comma","Trailing"]}',
        'f = [\n    "Comma",\n    "Trailing",\n]\n',
        'f = [\n    "Comma",\n    "Trailing",\n]\n',
    )


def test_matches_tomllib_004() raises:
    _check(
        "g = [\n  1,\n  2, # comment\n]\n",
        '{"g":[1,2]}',
        "g = [\n    1,\n    2,\n]\n",
        "g = [\n    1,\n    2,\n]\n",
    )
    _check(
        "empty = []\nnested_empty = [[], []]\n",
        '{"empty":[],"nested_empty":[[],[]]}',
        "empty = []\nnested_empty = [\n    [],\n    [],\n]\n",
        "empty = []\nnested_empty = [\n    [],\n    [],\n]\n",
    )
    _check(
        'mixed = [1, "two", true, [3], { a = 1 }]\n',
        '{"mixed":[1,"two",true,[3],{"a":1}]}',
        (
            'mixed = [\n    1,\n    "two",\n    true,\n    [\n        3,\n   '
            " ],\n    { a = 1 },\n]\n"
        ),
        (
            'mixed = [\n    1,\n    "two",\n    true,\n    [\n        3,\n   '
            " ],\n    { a = 1 },\n]\n"
        ),
    )
    _check(
        "[table]\n",
        '{"table":{}}',
        "[table]\n",
        "[table]\n",
    )
    _check(
        (
            '[table-1]\nkey1 = "some string"\nkey2 = 123\n\n[table-2]\nkey1 ='
            ' "another"\nkey2 = 456\n'
        ),
        (
            '{"table-1":{"key1":"some'
            ' string","key2":123},"table-2":{"key1":"another","key2":456}}'
        ),
        (
            '[table-1]\nkey1 = "some string"\nkey2 = 123\n\n[table-2]\nkey1 ='
            ' "another"\nkey2 = 456\n'
        ),
        (
            '[table-1]\nkey1 = "some string"\nkey2 = 123\n\n[table-2]\nkey1 ='
            ' "another"\nkey2 = 456\n'
        ),
    )
    _check(
        '[dog."tater.man"]\ntype.name = "pug"\n',
        '{"dog":{"tater.man":{"type":{"name":"pug"}}}}',
        '[dog."tater.man".type]\nname = "pug"\n',
        '[dog."tater.man".type]\nname = "pug"\n',
    )
    _check(
        "[a.b.c]\nx = 1\n",
        '{"a":{"b":{"c":{"x":1}}}}',
        "[a.b.c]\nx = 1\n",
        "[a.b.c]\nx = 1\n",
    )
    _check(
        "[x.y.z.w]\n[x]\n",
        '{"x":{"y":{"z":{"w":{}}}}}',
        "[x.y.z.w]\n",
        "[x.y.z.w]\n",
    )


def test_matches_tomllib_005() raises:
    _check(
        '[fruit]\napple.color = "red"\napple.taste.sweet = true\n',
        '{"fruit":{"apple":{"color":"red","taste":{"sweet":true}}}}',
        '[fruit.apple]\ncolor = "red"\n\n[fruit.apple.taste]\nsweet = true\n',
        '[fruit.apple]\ncolor = "red"\n\n[fruit.apple.taste]\nsweet = true\n',
    )
    _check(
        'name = { first = "Tom", last = "Preston-Werner" }\n',
        '{"name":{"first":"Tom","last":"Preston-Werner"}}',
        '[name]\nfirst = "Tom"\nlast = "Preston-Werner"\n',
        '[name]\nfirst = "Tom"\nlast = "Preston-Werner"\n',
    )
    _check(
        "point = { x = 1, y = 2 }\n",
        '{"point":{"x":1,"y":2}}',
        "[point]\nx = 1\ny = 2\n",
        "[point]\nx = 1\ny = 2\n",
    )
    _check(
        'animal = { type.name = "pug" }\n',
        '{"animal":{"type":{"name":"pug"}}}',
        '[animal.type]\nname = "pug"\n',
        '[animal.type]\nname = "pug"\n',
    )
    _check(
        "empty_inline = {}\n",
        '{"empty_inline":{}}',
        "[empty_inline]\n",
        "[empty_inline]\n",
    )
    _check(
        (
            '[[products]]\nname = "Hammer"\nsku ='
            ' 738594937\n\n[[products]]\n\n[[products]]\nname = "Nail"\nsku ='
            " 284758393\n"
        ),
        '{"products":[{"name":"Hammer","sku":738594937},{},{"name":"Nail","sku":284758393}]}',
        (
            'products = [\n    { name = "Hammer", sku = 738594937 },\n    {},\n'
            '    { name = "Nail", sku = 284758393 },\n]\n'
        ),
        (
            'products = [\n    { name = "Hammer", sku = 738594937 },\n    {},\n'
            '    { name = "Nail", sku = 284758393 },\n]\n'
        ),
    )
    _check(
        (
            '[[fruits]]\nname = "apple"\n\n[fruits.physical]\ncolor ='
            ' "red"\nshape = "round"\n\n[[fruits.varieties]]\nname = "red'
            ' delicious"\n\n[[fruits.varieties]]\nname = "granny smith"\n'
        ),
        (
            '{"fruits":[{"name":"apple","physical":{"color":"red","shape":"round"},"varieties":[{"name":"red'
            ' delicious"},{"name":"granny smith"}]}]}'
        ),
        (
            '[[fruits]]\nname = "apple"\nvarieties = [\n    { name = "red'
            ' delicious" },\n    { name = "granny smith"'
            ' },\n]\n\n[fruits.physical]\ncolor = "red"\nshape = "round"\n'
        ),
        (
            '[[fruits]]\nname = "apple"\nvarieties = [\n    { name = "red'
            ' delicious" },\n    { name = "granny smith"'
            ' },\n]\n\n[fruits.physical]\ncolor = "red"\nshape = "round"\n'
        ),
    )
    _check(
        "[[a]]\nx = [1, 2, 3]\n",
        '{"a":[{"x":[1,2,3]}]}',
        "[[a]]\nx = [\n    1,\n    2,\n    3,\n]\n",
        "[[a]]\nx = [\n    1,\n    2,\n    3,\n]\n",
    )


def test_matches_tomllib_006() raises:
    _check(
        (
            "[[p]]\nk ="
            ' "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"\n'
        ),
        '{"p":[{"k":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}]}',
        (
            "p = [\n    { k ="
            ' "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"'
            " },\n]\n"
        ),
        (
            "p = [\n    { k ="
            ' "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"'
            " },\n]\n"
        ),
    )
    _check(
        (
            "[[p]]\nk ="
            ' "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"\n'
        ),
        '{"p":[{"k":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}]}',
        (
            "[[p]]\nk ="
            ' "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"\n'
        ),
        (
            "[[p]]\nk ="
            ' "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"\n'
        ),
    )
    _check(
        'a = """abc""""\n',
        '{"a":"abc\\""}',
        'a = "abc\\""\n',
        'a = "abc\\""\n',
    )
    _check(
        'a = """abc"""""\n',
        '{"a":"abc\\"\\""}',
        'a = "abc\\"\\""\n',
        'a = "abc\\"\\""\n',
    )
    _check(
        "a = '''abc''''\n",
        '{"a":"abc\'"}',
        'a = "abc\'"\n',
        'a = "abc\'"\n',
    )
    _check(
        "a = '''abc'''''\n",
        '{"a":"abc\'\'"}',
        "a = \"abc''\"\n",
        "a = \"abc''\"\n",
    )
    _check(
        'a = """a""b"""\n',
        '{"a":"a\\"\\"b"}',
        'a = "a\\"\\"b"\n',
        'a = "a\\"\\"b"\n',
    )
    _check(
        "a = \"\"\"\"\"\"\nb = ''''''\n",
        '{"a":"","b":""}',
        'a = ""\nb = ""\n',
        'a = ""\nb = ""\n',
    )


def test_matches_tomllib_007() raises:
    _check(
        'a = "\\u0000"\nb = "\\uD7FF"\nc = "\\uE000"\nd = "\\U0010FFFF"\n',
        '{"a":"\\u0000","b":"\\ud7ff","c":"\\ue000","d":"\\udbff\\udfff"}',
        'a = "\\u0000"\nb = "퟿"\nc = ""\nd = "􏿿"\n',
        'a = "\\u0000"\nb = "퟿"\nc = ""\nd = "􏿿"\n',
    )
    _check(
        (
            "a = 9223372036854775807\nb = -9223372036854775808\nc ="
            " 0x7FFFFFFFFFFFFFFF\n"
        ),
        '{"a":9223372036854775807,"b":-9223372036854775808,"c":9223372036854775807}',
        (
            "a = 9223372036854775807\nb = -9223372036854775808\nc ="
            " 9223372036854775807\n"
        ),
        (
            "a = 9223372036854775807\nb = -9223372036854775808\nc ="
            " 9223372036854775807\n"
        ),
    )
    _check(
        (
            'a = "line\\nbreak"\nb = "carriage\\r\\nreturn"\nc ='
            ' "ctrl\\u0001char"\n'
        ),
        '{"a":"line\\nbreak","b":"carriage\\r\\nreturn","c":"ctrl\\u0001char"}',
        (
            'a = "line\\nbreak"\nb = "carriage\\r\\nreturn"\nc ='
            ' "ctrl\\u0001char"\n'
        ),
        (
            'a = """\nline\nbreak"""\nb = """\ncarriage\nreturn"""\nc ='
            ' "ctrl\\u0001char"\n'
        ),
    )
    _check(
        'a = "tab\\there"\nb = "del\\u007f"\n',
        '{"a":"tab\\there","b":"del\\u007f"}',
        'a = "tab\there"\nb = "del\\u007f"\n',
        'a = "tab\there"\nb = "del\\u007f"\n',
    )
    _check(
        (
            '["with space8"]\nk15 = [\n    { b15 = "with spaces" },\n    [\n   '
            "     -53,\n        -210,\n    ],\n    false,\n]\nk10 = true\n"
        ),
        (
            '{"with space8":{"k15":[{"b15":"with'
            ' spaces"},[-53,-210],false],"k10":true}}'
        ),
        (
            '["with space8"]\nk15 = [\n    { b15 = "with spaces" },\n    [\n   '
            "     -53,\n        -210,\n    ],\n    false,\n]\nk10 = true\n"
        ),
        (
            '["with space8"]\nk15 = [\n    { b15 = "with spaces" },\n    [\n   '
            "     -53,\n        -210,\n    ],\n    false,\n]\nk10 = true\n"
        ),
    )
    _check(
        'a16 = "say \\"hi\\""\n',
        '{"a16":"say \\"hi\\""}',
        'a16 = "say \\"hi\\""\n',
        'a16 = "say \\"hi\\""\n',
    )
    _check(
        "x12 = []\n",
        '{"x12":[]}',
        "x12 = []\n",
        "x12 = []\n",
    )
    _check(
        '0 = []\nk12 = "日本語"\nnested7 = "tab\there"\n',
        '{"0":[],"k12":"\\u65e5\\u672c\\u8a9e","nested7":"tab\\there"}',
        '0 = []\nk12 = "日本語"\nnested7 = "tab\there"\n',
        '0 = []\nk12 = "日本語"\nnested7 = "tab\there"\n',
    )


def test_matches_tomllib_008() raises:
    _check(
        (
            '0 = -9.9551\nb1 = -708\nkey0 = """\ncrlf\nhere"""\n\n[key4]\nk112'
            ' = "say \\"hi\\""\n\n[key4.k116]\nlong_key_name14 = true\nk115 ='
            " true\n"
        ),
        (
            '{"0":-9.9551,"b1":-708,"key0":"crlf\\nhere","key4":{"k112":"say'
            ' \\"hi\\"","k116":{"long_key_name14":true,"k115":true}}}'
        ),
        (
            '0 = -9.9551\nb1 = -708\nkey0 = "crlf\\nhere"\n\n[key4]\nk112 ='
            ' "say \\"hi\\""\n\n[key4.k116]\nlong_key_name14 = true\nk115 ='
            " true\n"
        ),
        (
            '0 = -9.9551\nb1 = -708\nkey0 = """\ncrlf\nhere"""\n\n[key4]\nk112'
            ' = "say \\"hi\\""\n\n[key4.k116]\nlong_key_name14 = true\nk115 ='
            " true\n"
        ),
    )
    _check(
        'key12 = "123"\n',
        '{"key12":"123"}',
        'key12 = "123"\n',
        'key12 = "123"\n',
    )
    _check(
        (
            'a16 = 670\n"with space16" = []\nk118 = [\n    -71.8028,\n   '
            ' -144,\n    { b19 = "ctrl\\u0001char" },\n]\n\n[k117]\nk119 ='
            ' -27.1578\n\n[k117.key12]\n\n[k117."with space2"]\n'
        ),
        (
            '{"a16":670,"with'
            ' space16":[],"k118":[-71.8028,-144,{"b19":"ctrl\\u0001char"}],"k117":{"k119":-27.1578,"key12":{},"with'
            ' space2":{}}}'
        ),
        (
            'a16 = 670\n"with space16" = []\nk118 = [\n    -71.8028,\n   '
            ' -144,\n    { b19 = "ctrl\\u0001char" },\n]\n\n[k117]\nk119 ='
            ' -27.1578\n\n[k117.key12]\n\n[k117."with space2"]\n'
        ),
        (
            'a16 = 670\n"with space16" = []\nk118 = [\n    -71.8028,\n   '
            ' -144,\n    { b19 = "ctrl\\u0001char" },\n]\n\n[k117]\nk119 ='
            ' -27.1578\n\n[k117.key12]\n\n[k117."with space2"]\n'
        ),
    )
    _check(
        'nested15 = "true"\nx3 = true\n',
        '{"nested15":"true","x3":true}',
        'nested15 = "true"\nx3 = true\n',
        'nested15 = "true"\nx3 = true\n',
    )
    _check(
        "k17 = true\nx18 = 487\nx9 = 74.362\n\n[a6]\n",
        '{"k17":true,"x18":487,"x9":74.362,"a6":{}}',
        "k17 = true\nx18 = 487\nx9 = 74.362\n\n[a6]\n",
        "k17 = true\nx18 = 487\nx9 = 74.362\n\n[a6]\n",
    )
    _check(
        "[k116]\n",
        '{"k116":{}}',
        "[k116]\n",
        "[k116]\n",
    )
    _check(
        '6 = []\n16 = "tab\there"\na5 = -433\n',
        '{"6":[],"16":"tab\\there","a5":-433}',
        '6 = []\n16 = "tab\there"\na5 = -433\n',
        '6 = []\n16 = "tab\there"\na5 = -433\n',
    )
    _check(
        (
            "x18 = [\n    [\n        {},\n        -32.1058,\n        { nested2"
            ' = """\nline\nbreak""", b12 = 431 },\n    ],\n    -901,\n   '
            ' "",\n]\n'
        ),
        '{"x18":[[{},-32.1058,{"nested2":"line\\nbreak","b12":431}],-901,""]}',
        (
            "x18 = [\n    [\n        {},\n        -32.1058,\n        { nested2"
            ' = "line\\nbreak", b12 = 431 },\n    ],\n    -901,\n    "",\n]\n'
        ),
        (
            "x18 = [\n    [\n        {},\n        -32.1058,\n        { nested2"
            ' = """\nline\nbreak""", b12 = 431 },\n    ],\n    -901,\n   '
            ' "",\n]\n'
        ),
    )


def test_matches_tomllib_009() raises:
    _check(
        '[key6]\nx14 = "tab\there"\n',
        '{"key6":{"x14":"tab\\there"}}',
        '[key6]\nx14 = "tab\there"\n',
        '[key6]\nx14 = "tab\there"\n',
    )
    _check(
        (
            'a13 = "123"\n\n[nested11]\nk119 = -924\nnested0 ='
            ' -25\n\n[nested11.k11]\n9 = [\n    "with spaces",\n   '
            ' """\nline\nbreak""",\n    "plain",\n]\nk12 = "日本語"\n7 = []\n'
        ),
        (
            '{"a13":"123","nested11":{"k119":-924,"nested0":-25,"k11":{"9":["with'
            ' spaces","line\\nbreak","plain"],"k12":"\\u65e5\\u672c\\u8a9e","7":[]}}}'
        ),
        (
            'a13 = "123"\n\n[nested11]\nk119 = -924\nnested0 ='
            ' -25\n\n[nested11.k11]\n9 = [\n    "with spaces",\n   '
            ' "line\\nbreak",\n    "plain",\n]\nk12 = "日本語"\n7 = []\n'
        ),
        (
            'a13 = "123"\n\n[nested11]\nk119 = -924\nnested0 ='
            ' -25\n\n[nested11.k11]\n9 = [\n    "with spaces",\n   '
            ' """\nline\nbreak""",\n    "plain",\n]\nk12 = "日本語"\n7 = []\n'
        ),
    )
    _check(
        (
            "a4 = -61.1341\n\n[x8]\nlong_key_name13 = 219\nk117 = [\n    [\n   "
            '     "with spaces",\n    ],\n]\n\n[x8.b8]\n'
        ),
        (
            '{"a4":-61.1341,"x8":{"long_key_name13":219,"k117":[["with'
            ' spaces"]],"b8":{}}}'
        ),
        (
            "a4 = -61.1341\n\n[x8]\nlong_key_name13 = 219\nk117 = [\n    [\n   "
            '     "with spaces",\n    ],\n]\n\n[x8.b8]\n'
        ),
        (
            "a4 = -61.1341\n\n[x8]\nlong_key_name13 = 219\nk117 = [\n    [\n   "
            '     "with spaces",\n    ],\n]\n\n[x8.b8]\n'
        ),
    )
    _check(
        "[x6]\n",
        '{"x6":{}}',
        "[x6]\n",
        "[x6]\n",
    )
    _check(
        (
            'b3 = 53\n10 = [\n    { "with space17" = "日本語" },\n    [\n       '
            ' "",\n    ],\n    "1.5",\n]\n'
        ),
        '{"b3":53,"10":[{"with space17":"\\u65e5\\u672c\\u8a9e"},[""],"1.5"]}',
        (
            'b3 = 53\n10 = [\n    { "with space17" = "日本語" },\n    [\n       '
            ' "",\n    ],\n    "1.5",\n]\n'
        ),
        (
            'b3 = 53\n10 = [\n    { "with space17" = "日本語" },\n    [\n       '
            ' "",\n    ],\n    "1.5",\n]\n'
        ),
    )
    _check(
        (
            'a2 = "  padded "\nlong_key_name1 = [\n    [\n        [\n          '
            "  true,\n            -99.0141,\n        ],\n        [\n           "
            ' false,\n            "it\'s",\n            false,\n        ],\n   '
            " ],\n]\na10 = -305\n"
        ),
        (
            '{"a2":"  padded'
            ' ","long_key_name1":[[[true,-99.0141],[false,"it\'s",false]]],"a10":-305}'
        ),
        (
            'a2 = "  padded "\nlong_key_name1 = [\n    [\n        [\n          '
            "  true,\n            -99.0141,\n        ],\n        [\n           "
            ' false,\n            "it\'s",\n            false,\n        ],\n   '
            " ],\n]\na10 = -305\n"
        ),
        (
            'a2 = "  padded "\nlong_key_name1 = [\n    [\n        [\n          '
            "  true,\n            -99.0141,\n        ],\n        [\n           "
            ' false,\n            "it\'s",\n            false,\n        ],\n   '
            " ],\n]\na10 = -305\n"
        ),
    )
    _check(
        '"with space14" = []\n\n[k111]\n',
        '{"with space14":[],"k111":{}}',
        '"with space14" = []\n\n[k111]\n',
        '"with space14" = []\n\n[k111]\n',
    )
    _check(
        "b3 = []\nx0 = 642\n",
        '{"b3":[],"x0":642}',
        "b3 = []\nx0 = 642\n",
        "b3 = []\nx0 = 642\n",
    )


def test_matches_tomllib_010() raises:
    _check(
        (
            'a17 = "it\'s"\nb19 = [\n    [],\n]\nk112 = -540\n\n["with'
            ' space3"]\nlong_key_name4 = [\n    [\n        266,\n       '
            " 27.0616,\n        -897,\n    ],\n    true,\n    [],\n]\nkey11 ="
            ' -17.5803\n\n["with space3"."with space16"]\n1 ='
            ' "ctrl\\u0001char"\n'
        ),
        (
            '{"a17":"it\'s","b19":[[]],"k112":-540,"with'
            ' space3":{"long_key_name4":[[266,27.0616,-897],true,[]],"key11":-17.5803,"with'
            ' space16":{"1":"ctrl\\u0001char"}}}'
        ),
        (
            'a17 = "it\'s"\nb19 = [\n    [],\n]\nk112 = -540\n\n["with'
            ' space3"]\nlong_key_name4 = [\n    [\n        266,\n       '
            " 27.0616,\n        -897,\n    ],\n    true,\n    [],\n]\nkey11 ="
            ' -17.5803\n\n["with space3"."with space16"]\n1 ='
            ' "ctrl\\u0001char"\n'
        ),
        (
            'a17 = "it\'s"\nb19 = [\n    [],\n]\nk112 = -540\n\n["with'
            ' space3"]\nlong_key_name4 = [\n    [\n        266,\n       '
            " 27.0616,\n        -897,\n    ],\n    true,\n    [],\n]\nkey11 ="
            ' -17.5803\n\n["with space3"."with space16"]\n1 ='
            ' "ctrl\\u0001char"\n'
        ),
    )
    _check(
        (
            '[b2.17."with space1"]\nb4 = -204\nlong_key_name12 ='
            ' -99.1842\n\n["with space15".long_key_name13]\n5 = []\n\n["with'
            ' space15".long_key_name13.k119]\n\n["with'
            ' space15".long_key_name13.13]\nx18 = -62.5365\nk111 = -960\nkey17'
            ' = "plain"\n\n["with space15".b16]\nkey4 = []\nnested4 ='
            ' false\n\n["with space15".b16.6]\na16 = 60.6728\n'
        ),
        (
            '{"b2":{"17":{"with'
            ' space1":{"b4":-204,"long_key_name12":-99.1842}}},"with'
            ' space15":{"long_key_name13":{"5":[],"k119":{},"13":{"x18":-62.5365,"k111":-960,"key17":"plain"}},"b16":{"key4":[],"nested4":false,"6":{"a16":60.6728}}}}'
        ),
        (
            '[b2.17."with space1"]\nb4 = -204\nlong_key_name12 ='
            ' -99.1842\n\n["with space15".long_key_name13]\n5 = []\n\n["with'
            ' space15".long_key_name13.k119]\n\n["with'
            ' space15".long_key_name13.13]\nx18 = -62.5365\nk111 = -960\nkey17'
            ' = "plain"\n\n["with space15".b16]\nkey4 = []\nnested4 ='
            ' false\n\n["with space15".b16.6]\na16 = 60.6728\n'
        ),
        (
            '[b2.17."with space1"]\nb4 = -204\nlong_key_name12 ='
            ' -99.1842\n\n["with space15".long_key_name13]\n5 = []\n\n["with'
            ' space15".long_key_name13.k119]\n\n["with'
            ' space15".long_key_name13.13]\nx18 = -62.5365\nk111 = -960\nkey17'
            ' = "plain"\n\n["with space15".b16]\nkey4 = []\nnested4 ='
            ' false\n\n["with space15".b16.6]\na16 = 60.6728\n'
        ),
    )
    _check(
        (
            '18 = [\n    false,\n    { "with space0" = true, a10 = {}, a6 = []'
            ' },\n]\nnested4 = -59\n\n[a7."with'
            ' space15"]\n\n[a7.3.3]\n\n[nested6]\n'
        ),
        (
            '{"18":[false,{"with'
            ' space0":true,"a10":{},"a6":[]}],"nested4":-59,"a7":{"with'
            ' space15":{},"3":{"3":{}}},"nested6":{}}'
        ),
        (
            '18 = [\n    false,\n    { "with space0" = true, a10 = {}, a6 = []'
            ' },\n]\nnested4 = -59\n\n[a7."with'
            ' space15"]\n\n[a7.3.3]\n\n[nested6]\n'
        ),
        (
            '18 = [\n    false,\n    { "with space0" = true, a10 = {}, a6 = []'
            ' },\n]\nnested4 = -59\n\n[a7."with'
            ' space15"]\n\n[a7.3.3]\n\n[nested6]\n'
        ),
    )
    _check(
        "nested12 = true\nx2 = -880\n",
        '{"nested12":true,"x2":-880}',
        "nested12 = true\nx2 = -880\n",
        "nested12 = true\nx2 = -880\n",
    )
    _check(
        (
            '[b16]\nlong_key_name7 = [\n    "123",\n    "back\\\\slash",\n   '
            ' 427,\n]\n\n[b16."with space9".a9]\nlong_key_name1 ='
            ' """\nline\nbreak"""\n\n[b16."with space9".3]\n2 = -501\nb11 ='
            " 74\n\n[b16.k111.2]\nkey8 = false\n"
        ),
        (
            '{"b16":{"long_key_name7":["123","back\\\\slash",427],"with'
            ' space9":{"a9":{"long_key_name1":"line\\nbreak"},"3":{"2":-501,"b11":74}},"k111":{"2":{"key8":false}}}}'
        ),
        (
            '[b16]\nlong_key_name7 = [\n    "123",\n    "back\\\\slash",\n   '
            ' 427,\n]\n\n[b16."with space9".a9]\nlong_key_name1 ='
            ' "line\\nbreak"\n\n[b16."with space9".3]\n2 = -501\nb11 ='
            " 74\n\n[b16.k111.2]\nkey8 = false\n"
        ),
        (
            '[b16]\nlong_key_name7 = [\n    "123",\n    "back\\\\slash",\n   '
            ' 427,\n]\n\n[b16."with space9".a9]\nlong_key_name1 ='
            ' """\nline\nbreak"""\n\n[b16."with space9".3]\n2 = -501\nb11 ='
            " 74\n\n[b16.k111.2]\nkey8 = false\n"
        ),
    )
    _check(
        'long_key_name7 = "line\\nbreak"\n',
        '{"long_key_name7":"line\\nbreak"}',
        'long_key_name7 = "line\\nbreak"\n',
        'long_key_name7 = """\nline\nbreak"""\n',
    )
    _check(
        '[a8]\na8 = "123"\nk17 = "back\\\\slash"\n',
        '{"a8":{"a8":"123","k17":"back\\\\slash"}}',
        '[a8]\na8 = "123"\nk17 = "back\\\\slash"\n',
        '[a8]\na8 = "123"\nk17 = "back\\\\slash"\n',
    )
    _check(
        (
            "key14 = []\nnested10 = [\n    [],\n    [\n        { a17 = true"
            ' },\n    ],\n]\n\n["with space6"]\n\n[k111]\nnested0 ='
            " false\nlong_key_name1 = -414\n"
        ),
        (
            '{"key14":[],"nested10":[[],[{"a17":true}]],"with'
            ' space6":{},"k111":{"nested0":false,"long_key_name1":-414}}'
        ),
        (
            "key14 = []\nnested10 = [\n    [],\n    [\n        { a17 = true"
            ' },\n    ],\n]\n\n["with space6"]\n\n[k111]\nnested0 ='
            " false\nlong_key_name1 = -414\n"
        ),
        (
            "key14 = []\nnested10 = [\n    [],\n    [\n        { a17 = true"
            ' },\n    ],\n]\n\n["with space6"]\n\n[k111]\nnested0 ='
            " false\nlong_key_name1 = -414\n"
        ),
    )


def test_matches_tomllib_011() raises:
    _check(
        "long_key_name8 = -41.1111\n",
        '{"long_key_name8":-41.1111}',
        "long_key_name8 = -41.1111\n",
        "long_key_name8 = -41.1111\n",
    )
    _check(
        "18 = true\n",
        '{"18":true}',
        "18 = true\n",
        "18 = true\n",
    )
    _check(
        "b15 = []\nkey4 = 81.0643\nb17 = true\n\n[key13]\n",
        '{"b15":[],"key4":81.0643,"b17":true,"key13":{}}',
        "b15 = []\nkey4 = 81.0643\nb17 = true\n\n[key13]\n",
        "b15 = []\nkey4 = 81.0643\nb17 = true\n\n[key13]\n",
    )
    _check(
        (
            '17 = [\n    -464,\n]\n\n[key18]\nnested1 = "日本語"\n\n[b6]\nx16 ='
            ' """\ncrlf\nhere"""\n\n[key10]\nkey17 = 0.6678\n'
        ),
        '{"17":[-464],"key18":{"nested1":"\\u65e5\\u672c\\u8a9e"},"b6":{"x16":"crlf\\nhere"},"key10":{"key17":0.6678}}',
        (
            '17 = [\n    -464,\n]\n\n[key18]\nnested1 = "日本語"\n\n[b6]\nx16 ='
            ' "crlf\\nhere"\n\n[key10]\nkey17 = 0.6678\n'
        ),
        (
            '17 = [\n    -464,\n]\n\n[key18]\nnested1 = "日本語"\n\n[b6]\nx16 ='
            ' """\ncrlf\nhere"""\n\n[key10]\nkey17 = 0.6678\n'
        ),
    )
    _check(
        '11 = []\nx16 = [\n    { 12 = 17.1926, 18 = "", x10 = {} },\n]\n',
        '{"11":[],"x16":[{"12":17.1926,"18":"","x10":{}}]}',
        '11 = []\nx16 = [\n    { 12 = 17.1926, 18 = "", x10 = {} },\n]\n',
        '11 = []\nx16 = [\n    { 12 = 17.1926, 18 = "", x10 = {} },\n]\n',
    )
    _check(
        (
            'x2 = "tab\there"\n"with space8" = [\n    false,\n    {'
            ' long_key_name0 = [\n    "  padded ",\n    20.9381,\n   '
            ' "plain",\n] },\n    { x9 = true, x7 = { key1 = false }'
            ' },\n]\n"with space3" = "it\'s"\n\n[nested9]\nx6 = "with'
            ' spaces"\n8 = true\n'
        ),
        (
            '{"x2":"tab\\there","with space8":[false,{"long_key_name0":[" '
            ' padded ",20.9381,"plain"]},{"x9":true,"x7":{"key1":false}}],"with'
            ' space3":"it\'s","nested9":{"x6":"with spaces","8":true}}'
        ),
        (
            'x2 = "tab\there"\n"with space8" = [\n    false,\n    {'
            ' long_key_name0 = [\n    "  padded ",\n    20.9381,\n   '
            ' "plain",\n] },\n    { x9 = true, x7 = { key1 = false }'
            ' },\n]\n"with space3" = "it\'s"\n\n[nested9]\nx6 = "with'
            ' spaces"\n8 = true\n'
        ),
        (
            'x2 = "tab\there"\n"with space8" = [\n    false,\n    {'
            ' long_key_name0 = [\n    "  padded ",\n    20.9381,\n   '
            ' "plain",\n] },\n    { x9 = true, x7 = { key1 = false }'
            ' },\n]\n"with space3" = "it\'s"\n\n[nested9]\nx6 = "with'
            ' spaces"\n8 = true\n'
        ),
    )
    _check(
        "k19 = []\nk12 = -616\n",
        '{"k19":[],"k12":-616}',
        "k19 = []\nk12 = -616\n",
        "k19 = []\nk12 = -616\n",
    )
    _check(
        (
            "x3 = [\n    -272,\n    -479,\n    [\n        -44.9737,\n       "
            ' [],\n    ],\n]\nk116 = "tab\there"\na13 = [\n    [\n       '
            ' false,\n        "1.5",\n    ],\n    226,\n    20.656,\n]\n'
        ),
        '{"x3":[-272,-479,[-44.9737,[]]],"k116":"tab\\there","a13":[[false,"1.5"],226,20.656]}',
        (
            "x3 = [\n    -272,\n    -479,\n    [\n        -44.9737,\n       "
            ' [],\n    ],\n]\nk116 = "tab\there"\na13 = [\n    [\n       '
            ' false,\n        "1.5",\n    ],\n    226,\n    20.656,\n]\n'
        ),
        (
            "x3 = [\n    -272,\n    -479,\n    [\n        -44.9737,\n       "
            ' [],\n    ],\n]\nk116 = "tab\there"\na13 = [\n    [\n       '
            ' false,\n        "1.5",\n    ],\n    226,\n    20.656,\n]\n'
        ),
    )


def test_matches_tomllib_012() raises:
    _check(
        '"with space6" = true\n',
        '{"with space6":true}',
        '"with space6" = true\n',
        '"with space6" = true\n',
    )
    _check(
        '[nested2]\n"with space12" = []\n\n[nested2.key15]\nk111 = false\n',
        '{"nested2":{"with space12":[],"key15":{"k111":false}}}',
        '[nested2]\n"with space12" = []\n\n[nested2.key15]\nk111 = false\n',
        '[nested2]\n"with space12" = []\n\n[nested2.key15]\nk111 = false\n',
    )
    _check(
        (
            'k118 = "plain"\nlong_key_name13 = [\n    false,\n    [\n       '
            " true,\n        [\n            false,\n        ],\n       "
            " false,\n    ],\n]\n"
        ),
        '{"k118":"plain","long_key_name13":[false,[true,[false],false]]}',
        (
            'k118 = "plain"\nlong_key_name13 = [\n    false,\n    [\n       '
            " true,\n        [\n            false,\n        ],\n       "
            " false,\n    ],\n]\n"
        ),
        (
            'k118 = "plain"\nlong_key_name13 = [\n    false,\n    [\n       '
            " true,\n        [\n            false,\n        ],\n       "
            " false,\n    ],\n]\n"
        ),
    )
    _check(
        (
            'nested10 = -964\n5 = -30.863\n\n[x3]\na18 = "  padded "\na2 ='
            ' -28.5271\n\n[x3."with space11"]\n'
        ),
        (
            '{"nested10":-964,"5":-30.863,"x3":{"a18":"  padded'
            ' ","a2":-28.5271,"with space11":{}}}'
        ),
        (
            'nested10 = -964\n5 = -30.863\n\n[x3]\na18 = "  padded "\na2 ='
            ' -28.5271\n\n[x3."with space11"]\n'
        ),
        (
            'nested10 = -964\n5 = -30.863\n\n[x3]\na18 = "  padded "\na2 ='
            ' -28.5271\n\n[x3."with space11"]\n'
        ),
    )
    _check(
        (
            'long_key_name18 = 8.2603\n5 = [\n    71.2086,\n    [\n        " '
            ' padded ",\n        "日本語",\n        false,\n    ],\n   '
            ' "日本語",\n]\na8 = false\n\n[nested17]\n"with space17" ='
            ' 71.5252\nb19 = 955\n"with space18" = [\n    [\n        "日本語",\n  '
            '      7.5462,\n    ],\n    "line\\nbreak",\n]\n'
        ),
        (
            '{"long_key_name18":8.2603,"5":[71.2086,["  padded'
            ' ","\\u65e5\\u672c\\u8a9e",false],"\\u65e5\\u672c\\u8a9e"],"a8":false,"nested17":{"with'
            ' space17":71.5252,"b19":955,"with'
            ' space18":[["\\u65e5\\u672c\\u8a9e",7.5462],"line\\nbreak"]}}'
        ),
        (
            'long_key_name18 = 8.2603\n5 = [\n    71.2086,\n    [\n        " '
            ' padded ",\n        "日本語",\n        false,\n    ],\n   '
            ' "日本語",\n]\na8 = false\n\n[nested17]\n"with space17" ='
            ' 71.5252\nb19 = 955\n"with space18" = [\n    [\n        "日本語",\n  '
            '      7.5462,\n    ],\n    "line\\nbreak",\n]\n'
        ),
        (
            'long_key_name18 = 8.2603\n5 = [\n    71.2086,\n    [\n        " '
            ' padded ",\n        "日本語",\n        false,\n    ],\n   '
            ' "日本語",\n]\na8 = false\n\n[nested17]\n"with space17" ='
            ' 71.5252\nb19 = 955\n"with space18" = [\n    [\n        "日本語",\n  '
            '      7.5462,\n    ],\n    """\nline\nbreak""",\n]\n'
        ),
    )
    _check(
        (
            '"with space13" = [\n    [],\n    [\n        { 2 = false },\n   '
            ' ],\n    "日本語",\n]\nb18 = 737\n'
        ),
        '{"with space13":[[],[{"2":false}],"\\u65e5\\u672c\\u8a9e"],"b18":737}',
        (
            '"with space13" = [\n    [],\n    [\n        { 2 = false },\n   '
            ' ],\n    "日本語",\n]\nb18 = 737\n'
        ),
        (
            '"with space13" = [\n    [],\n    [\n        { 2 = false },\n   '
            ' ],\n    "日本語",\n]\nb18 = 737\n'
        ),
    )
    _check(
        'a14 = "true"\nkey2 = -4.7223\n\n[k19]\n',
        '{"a14":"true","key2":-4.7223,"k19":{}}',
        'a14 = "true"\nkey2 = -4.7223\n\n[k19]\n',
        'a14 = "true"\nkey2 = -4.7223\n\n[k19]\n',
    )
    _check(
        (
            "[a15]\nlong_key_name0 = -193\n\n[a3]\nk11 = -238\n\n[a3.k16]\nkey3"
            " = 464\nkey14 = -587\n8 = []\n"
        ),
        '{"a15":{"long_key_name0":-193},"a3":{"k11":-238,"k16":{"key3":464,"key14":-587,"8":[]}}}',
        (
            "[a15]\nlong_key_name0 = -193\n\n[a3]\nk11 = -238\n\n[a3.k16]\nkey3"
            " = 464\nkey14 = -587\n8 = []\n"
        ),
        (
            "[a15]\nlong_key_name0 = -193\n\n[a3]\nk11 = -238\n\n[a3.k16]\nkey3"
            " = 464\nkey14 = -587\n8 = []\n"
        ),
    )


def test_matches_tomllib_013() raises:
    _check(
        (
            'x7 = [\n    [\n        """\nline\nbreak""",\n    ],\n    [\n      '
            '  { 5 = 54.5653 },\n        [\n            "back\\\\slash",\n     '
            '       false,\n        ],\n        {},\n    ],\n    "  padded'
            ' ",\n]\nk11 = false\n\n[10]\n"with space2" ='
            ' ""\n\n[10.nested0]\n17 = "1.5"\n'
        ),
        (
            '{"x7":[["line\\nbreak"],[{"5":54.5653},["back\\\\slash",false],{}],"'
            '  padded "],"k11":false,"10":{"with'
            ' space2":"","nested0":{"17":"1.5"}}}'
        ),
        (
            'x7 = [\n    [\n        "line\\nbreak",\n    ],\n    [\n        { 5'
            ' = 54.5653 },\n        [\n            "back\\\\slash",\n          '
            '  false,\n        ],\n        {},\n    ],\n    "  padded'
            ' ",\n]\nk11 = false\n\n[10]\n"with space2" ='
            ' ""\n\n[10.nested0]\n17 = "1.5"\n'
        ),
        (
            'x7 = [\n    [\n        """\nline\nbreak""",\n    ],\n    [\n      '
            '  { 5 = 54.5653 },\n        [\n            "back\\\\slash",\n     '
            '       false,\n        ],\n        {},\n    ],\n    "  padded'
            ' ",\n]\nk11 = false\n\n[10]\n"with space2" ='
            ' ""\n\n[10.nested0]\n17 = "1.5"\n'
        ),
    )
    _check(
        (
            '"with space11" = ""\n\n[b11]\n3 = "with'
            ' spaces"\n\n[b11.key17]\n\n[key19]\nkey13 ='
            ' "plain"\n\n[key19.k12]\n"with space4" ='
            ' 609\n\n[key19.k12.k115]\nb13 = "back\\\\slash"\n\n[x10]\nk13 ='
            ' 987\nk10 = "it\'s"\nnested1 = "1.5"\n'
        ),
        (
            '{"with space11":"","b11":{"3":"with'
            ' spaces","key17":{}},"key19":{"key13":"plain","k12":{"with'
            ' space4":609,"k115":{"b13":"back\\\\slash"}}},"x10":{"k13":987,"k10":"it\'s","nested1":"1.5"}}'
        ),
        (
            '"with space11" = ""\n\n[b11]\n3 = "with'
            ' spaces"\n\n[b11.key17]\n\n[key19]\nkey13 ='
            ' "plain"\n\n[key19.k12]\n"with space4" ='
            ' 609\n\n[key19.k12.k115]\nb13 = "back\\\\slash"\n\n[x10]\nk13 ='
            ' 987\nk10 = "it\'s"\nnested1 = "1.5"\n'
        ),
        (
            '"with space11" = ""\n\n[b11]\n3 = "with'
            ' spaces"\n\n[b11.key17]\n\n[key19]\nkey13 ='
            ' "plain"\n\n[key19.k12]\n"with space4" ='
            ' 609\n\n[key19.k12.k115]\nb13 = "back\\\\slash"\n\n[x10]\nk13 ='
            ' 987\nk10 = "it\'s"\nnested1 = "1.5"\n'
        ),
    )
    _check(
        "k115 = false\n",
        '{"k115":false}',
        "k115 = false\n",
        "k115 = false\n",
    )
    _check(
        (
            'long_key_name1 = [\n    285,\n    [\n        "1.5",\n        [],\n'
            '    ],\n]\n\n[nested12]\n\n[b12]\nb17 = "line\\nbreak"\nnested5 ='
            " 219\n"
        ),
        '{"long_key_name1":[285,["1.5",[]]],"nested12":{},"b12":{"b17":"line\\nbreak","nested5":219}}',
        (
            'long_key_name1 = [\n    285,\n    [\n        "1.5",\n        [],\n'
            '    ],\n]\n\n[nested12]\n\n[b12]\nb17 = "line\\nbreak"\nnested5 ='
            " 219\n"
        ),
        (
            'long_key_name1 = [\n    285,\n    [\n        "1.5",\n        [],\n'
            "    ],\n]\n\n[nested12]\n\n[b12]\nb17 ="
            ' """\nline\nbreak"""\nnested5 = 219\n'
        ),
    )
    _check(
        (
            '"with space13" = [\n    [],\n]\n\n[x2]\nlong_key_name7 = false\na0'
            ' = "ctrl\\u0001char"\n\n[nested9]\nb4 = false\na13 ='
            ' false\n\n[long_key_name16]\nb1 = "1.5"\n'
        ),
        (
            '{"with'
            ' space13":[[]],"x2":{"long_key_name7":false,"a0":"ctrl\\u0001char"},"nested9":{"b4":false,"a13":false},"long_key_name16":{"b1":"1.5"}}'
        ),
        (
            '"with space13" = [\n    [],\n]\n\n[x2]\nlong_key_name7 = false\na0'
            ' = "ctrl\\u0001char"\n\n[nested9]\nb4 = false\na13 ='
            ' false\n\n[long_key_name16]\nb1 = "1.5"\n'
        ),
        (
            '"with space13" = [\n    [],\n]\n\n[x2]\nlong_key_name7 = false\na0'
            ' = "ctrl\\u0001char"\n\n[nested9]\nb4 = false\na13 ='
            ' false\n\n[long_key_name16]\nb1 = "1.5"\n'
        ),
    )
    _check(
        "key1 = -26.9157\n",
        '{"key1":-26.9157}',
        "key1 = -26.9157\n",
        "key1 = -26.9157\n",
    )
    _check(
        (
            '"with space6" = 5.7906\n\n[k110]\n8 = "say \\"hi\\""\nk18 = [\n   '
            " [],\n]\n\n[k110.1]\n"
        ),
        '{"with space6":5.7906,"k110":{"8":"say \\"hi\\"","k18":[[]],"1":{}}}',
        (
            '"with space6" = 5.7906\n\n[k110]\n8 = "say \\"hi\\""\nk18 = [\n   '
            " [],\n]\n\n[k110.1]\n"
        ),
        (
            '"with space6" = 5.7906\n\n[k110]\n8 = "say \\"hi\\""\nk18 = [\n   '
            " [],\n]\n\n[k110.1]\n"
        ),
    )
    _check(
        (
            '7 = []\n"with space11" = true\n\n["with space0"]\nk17 ='
            ' -790\n\n["with space0".x16]\n"with space14" ='
            ' "ctrl\\u0001char"\na11 = 28.3775\n'
        ),
        (
            '{"7":[],"with space11":true,"with space0":{"k17":-790,"x16":{"with'
            ' space14":"ctrl\\u0001char","a11":28.3775}}}'
        ),
        (
            '7 = []\n"with space11" = true\n\n["with space0"]\nk17 ='
            ' -790\n\n["with space0".x16]\n"with space14" ='
            ' "ctrl\\u0001char"\na11 = 28.3775\n'
        ),
        (
            '7 = []\n"with space11" = true\n\n["with space0"]\nk17 ='
            ' -790\n\n["with space0".x16]\n"with space14" ='
            ' "ctrl\\u0001char"\na11 = 28.3775\n'
        ),
    )


def test_matches_tomllib_014() raises:
    _check(
        'key19 = "1.5"\na17 = """\ncrlf\nhere"""\n',
        '{"key19":"1.5","a17":"crlf\\nhere"}',
        'key19 = "1.5"\na17 = "crlf\\nhere"\n',
        'key19 = "1.5"\na17 = """\ncrlf\nhere"""\n',
    )
    _check(
        (
            '[b9]\nk10 = "123"\nnested19 = true\n\n[b9.long_key_name14]\nx19 ='
            " [\n    false,\n    false,\n]\n"
        ),
        '{"b9":{"k10":"123","nested19":true,"long_key_name14":{"x19":[false,false]}}}',
        (
            '[b9]\nk10 = "123"\nnested19 = true\n\n[b9.long_key_name14]\nx19 ='
            " [\n    false,\n    false,\n]\n"
        ),
        (
            '[b9]\nk10 = "123"\nnested19 = true\n\n[b9.long_key_name14]\nx19 ='
            " [\n    false,\n    false,\n]\n"
        ),
    )
    _check(
        "10 = false\n",
        '{"10":false}',
        "10 = false\n",
        "10 = false\n",
    )
    _check(
        (
            'nested14 = false\nb2 = "1.5"\n\n[12]\n\n[[key6]]\nnested14 ='
            ' ""\n\n[[key6]]\nb2 = -61.8971\n"with space19" = false\nx2 = [\n  '
            '  "it\'s",\n    -22.0079,\n]\n'
        ),
        (
            '{"nested14":false,"b2":"1.5","12":{},"key6":[{"nested14":""},{"b2":-61.8971,"with'
            ' space19":false,"x2":["it\'s",-22.0079]}]}'
        ),
        (
            'nested14 = false\nb2 = "1.5"\n\n[12]\n\n[[key6]]\nnested14 ='
            ' ""\n\n[[key6]]\nb2 = -61.8971\n"with space19" = false\nx2 = [\n  '
            '  "it\'s",\n    -22.0079,\n]\n'
        ),
        (
            'nested14 = false\nb2 = "1.5"\n\n[12]\n\n[[key6]]\nnested14 ='
            ' ""\n\n[[key6]]\nb2 = -61.8971\n"with space19" = false\nx2 = [\n  '
            '  "it\'s",\n    -22.0079,\n]\n'
        ),
    )
    _check(
        'key13 = """\ncrlf\nhere"""\na11 = "true"\n',
        '{"key13":"crlf\\nhere","a11":"true"}',
        'key13 = "crlf\\nhere"\na11 = "true"\n',
        'key13 = """\ncrlf\nhere"""\na11 = "true"\n',
    )
    _check(
        '"with space8" = -6.935\n',
        '{"with space8":-6.935}',
        '"with space8" = -6.935\n',
        '"with space8" = -6.935\n',
    )
    _check(
        (
            "b12 = false\nk115 = -28.6254\n\n[a14.k11]\nlong_key_name9 = [\n   "
            ' "true",\n    -47.965,\n    -21.3162,\n]\n'
        ),
        '{"b12":false,"k115":-28.6254,"a14":{"k11":{"long_key_name9":["true",-47.965,-21.3162]}}}',
        (
            "b12 = false\nk115 = -28.6254\n\n[a14.k11]\nlong_key_name9 = [\n   "
            ' "true",\n    -47.965,\n    -21.3162,\n]\n'
        ),
        (
            "b12 = false\nk115 = -28.6254\n\n[a14.k11]\nlong_key_name9 = [\n   "
            ' "true",\n    -47.965,\n    -21.3162,\n]\n'
        ),
    )
    _check(
        '"with space2" = 8.9028\n10 = [\n    "ctrl\\u0001char",\n    [],\n]\n',
        '{"with space2":8.9028,"10":["ctrl\\u0001char",[]]}',
        '"with space2" = 8.9028\n10 = [\n    "ctrl\\u0001char",\n    [],\n]\n',
        '"with space2" = 8.9028\n10 = [\n    "ctrl\\u0001char",\n    [],\n]\n',
    )


def test_rejects_like_tomllib_000() raises:
    with assert_raises():
        _ = loads("= 1\n")
    with assert_raises():
        _ = loads("a =\n")
    with assert_raises():
        _ = loads("a = 1\nb\n")
    with assert_raises():
        _ = loads("a = 1 2\n")
    with assert_raises():
        _ = loads("a = 1\na = 2\n")
    with assert_raises():
        _ = loads("[a]\n[a]\n")
    with assert_raises():
        _ = loads("a.b = 1\n[a]\n")
    with assert_raises():
        _ = loads("[a]\nb = 1\n[a.b]\nc = 2\n")


def test_rejects_like_tomllib_001() raises:
    with assert_raises():
        _ = loads("a = [1, 2\n")
    with assert_raises():
        _ = loads("a = { b = 1\n")
    with assert_raises():
        _ = loads("a = { b = 1, }\n")
    with assert_raises():
        _ = loads("a = { b = 1\nc = 2 }\n")
    with assert_raises():
        _ = loads('a = "unterminated\n')
    with assert_raises():
        _ = loads("a = 'unterminated\n")
    with assert_raises():
        _ = loads('a = "bad \\escape"\n')
    with assert_raises():
        _ = loads('a = "\\u00"\n')


def test_rejects_like_tomllib_002() raises:
    with assert_raises():
        _ = loads("a = 01\n")
    with assert_raises():
        _ = loads("a = 1.\n")
    with assert_raises():
        _ = loads("a = .1\n")
    with assert_raises():
        _ = loads("a = 1__0\n")
    with assert_raises():
        _ = loads("a = 0x\n")
    with assert_raises():
        _ = loads("a = truthy\n")
    with assert_raises():
        _ = loads("[]\n")
    with assert_raises():
        _ = loads("[a.]\n")


def test_rejects_like_tomllib_003() raises:
    with assert_raises():
        _ = loads("[[a]\n")
    with assert_raises():
        _ = loads("a = 1\n[[a]]\n")
    with assert_raises():
        _ = loads("[a]\n[[a]]\n")
    with assert_raises():
        _ = loads("a = { b = 1 }\n[a.c]\nd = 2\n")
    with assert_raises():
        _ = loads("a = [1]\n[[a]]\n")
    with assert_raises():
        _ = loads('a = "\\x7f"\n')
    with assert_raises():
        _ = loads('a = "\\uD800"\n')
    with assert_raises():
        _ = loads('a = "\\uDFFF"\n')


def test_rejects_like_tomllib_004() raises:
    with assert_raises():
        _ = loads('a = "\\U00110000"\n')
    with assert_raises():
        _ = loads('a = "\\UFFFFFFFF"\n')
    with assert_raises():
        _ = loads("a = 1\na.b = 2\n")
    with assert_raises():
        _ = loads("a = 1\n[a.b]\n")
    with assert_raises():
        _ = loads('a = "x"\na.b = 2\n')
    with assert_raises():
        _ = loads("a = [1]\n[a.b]\nc = 1\n")
    with assert_raises():
        _ = loads("a = [{ b = 1 }]\n[a.c]\nd = 1\n")
    with assert_raises():
        _ = loads("a = []\n[a.b]\nc = 1\n")


def test_rejects_like_tomllib_005() raises:
    with assert_raises():
        _ = loads("a = 1\n[[a]]\n")
    with assert_raises():
        _ = loads("[a]\nb = 1\n[a.b]\n")
    with assert_raises():
        _ = loads("a = 2023-99-99\n")
    with assert_raises():
        _ = loads("a = 12:99:99\n")
    with assert_raises():
        _ = loads("a = 2023-01-01junk\n")
    with assert_raises():
        _ = loads("a = 2023-02-30\n")
    with assert_raises():
        _ = loads("a = 2023-02-29\n")
    with assert_raises():
        _ = loads("a = 1900-02-29\n")


def test_rejects_like_tomllib_006() raises:
    with assert_raises():
        _ = loads("a = 2023-04-31\n")
    with assert_raises():
        _ = loads("a = 24:00:00\n")
    with assert_raises():
        _ = loads("a = 07:32\n")
    with assert_raises():
        _ = loads("a = 1979-05-27T07:32:00+25:00\n")
    with assert_raises():
        _ = loads("a = 1979-05-27T\n")
    with assert_raises():
        _ = loads("a = 1_e2\n")
    with assert_raises():
        _ = loads("a = 1e_2\n")
    with assert_raises():
        _ = loads("a = 1._0\n")


def test_rejects_like_tomllib_007() raises:
    with assert_raises():
        _ = loads("a = 0x_1\n")
    with assert_raises():
        _ = loads("a = 0b_1\n")
    with assert_raises():
        _ = loads("a = 1_.0\n")
    with assert_raises():
        _ = loads("a = 0X1\n")
    with assert_raises():
        _ = loads("a = 0O17\n")
    with assert_raises():
        _ = loads("a = 0B1\n")
    with assert_raises():
        _ = loads("a = +0x1\n")
    with assert_raises():
        _ = loads("a = -0x1\n")


def test_rejects_like_tomllib_008() raises:
    with assert_raises():
        _ = loads('a = """abc""""""\n')
    with assert_raises():
        _ = loads("a = '''abc''''''\n")


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
